/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import javax.swing.JOptionPane;

/**
 *
 * @author Darío
 */
public class gestion_proveedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestion_proveedores.class.getName());

    /**
     * Creates new form gestion_provedores
     */
    public gestion_proveedores() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Pnlinicio = new javax.swing.JPanel();
        PnlEncabezado = new javax.swing.JPanel();
        LblFoto = new javax.swing.JLabel();
        LblTItulo = new javax.swing.JLabel();
        PnlUsuario = new javax.swing.JPanel();
        LblUsuario = new javax.swing.JLabel();
        BtnCerrarSesion = new javax.swing.JButton();
        LblPerfil = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PnlProveedores = new javax.swing.JPanel();
        LblFoto1 = new javax.swing.JLabel();
        BtnAgregar1 = new javax.swing.JButton();
        BtnConsultar1 = new javax.swing.JButton();
        BtnBaja1 = new javax.swing.JButton();
        LblFoto2 = new javax.swing.JLabel();
        BtnAgregar2 = new javax.swing.JButton();
        BtnConsultar2 = new javax.swing.JButton();
        BtnBaja2 = new javax.swing.JButton();
        LblFoto3 = new javax.swing.JLabel();
        BtnAgregar3 = new javax.swing.JButton();
        BtnConsultar3 = new javax.swing.JButton();
        BtnBaja3 = new javax.swing.JButton();
        LblFoto5 = new javax.swing.JLabel();
        BtnAgregar5 = new javax.swing.JButton();
        BtnConsultar5 = new javax.swing.JButton();
        BtnBaja5 = new javax.swing.JButton();
        LblFoto7 = new javax.swing.JLabel();
        BtnAgregar6 = new javax.swing.JButton();
        BtnConsultar6 = new javax.swing.JButton();
        BtnBaja6 = new javax.swing.JButton();
        LblFoto6 = new javax.swing.JLabel();
        BtnAgregar7 = new javax.swing.JButton();
        BtnConsultar7 = new javax.swing.JButton();
        BtnBaja7 = new javax.swing.JButton();
        LblFoto8 = new javax.swing.JLabel();
        BtnAgregar8 = new javax.swing.JButton();
        BtnConsultar8 = new javax.swing.JButton();
        BtnBaja8 = new javax.swing.JButton();
        Lblfoto4 = new javax.swing.JLabel();
        BtnAgregar4 = new javax.swing.JButton();
        BtnConsultar4 = new javax.swing.JButton();
        BtnBaja4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pnlinicio.setBackground(new java.awt.Color(255, 255, 255));
        Pnlinicio.setLayout(new java.awt.BorderLayout());

        PnlEncabezado.setBackground(new java.awt.Color(102, 102, 102));
        PnlEncabezado.setLayout(new java.awt.GridBagLayout());

        LblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        PnlEncabezado.add(LblFoto, gridBagConstraints);

        LblTItulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        LblTItulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTItulo.setText("GESTIÓN DE PROOVEDORES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        PnlEncabezado.add(LblTItulo, gridBagConstraints);

        PnlUsuario.setBackground(new java.awt.Color(153, 153, 153));
        PnlUsuario.setLayout(new java.awt.GridBagLayout());

        LblUsuario.setText("Nombreyapellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        PnlUsuario.add(LblUsuario, gridBagConstraints);

        BtnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 51, 51));
        BtnCerrarSesion.setText("Cerrar sesión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        PnlUsuario.add(BtnCerrarSesion, gridBagConstraints);

        LblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobatito.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        PnlUsuario.add(LblPerfil, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.ipady = 91;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        PnlEncabezado.add(PnlUsuario, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIDA");
        jButton1.setPreferredSize(new java.awt.Dimension(176, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        PnlEncabezado.add(jButton1, gridBagConstraints);

        Pnlinicio.add(PnlEncabezado, java.awt.BorderLayout.PAGE_START);

        PnlProveedores.setBackground(new java.awt.Color(153, 255, 255));
        PnlProveedores.setLayout(new java.awt.GridBagLayout());

        LblFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cocacolaespuma.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(LblFoto1, gridBagConstraints);

        BtnAgregar1.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar1.setText("Agregar Producto");
        BtnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar1, gridBagConstraints);

        BtnConsultar1.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar1.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar1.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar1, gridBagConstraints);

        BtnBaja1.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja1.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja1.setText("Dar de Baja");
        BtnBaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBaja1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja1, gridBagConstraints);

        LblFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuetara.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(LblFoto2, gridBagConstraints);

        BtnAgregar2.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar2.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar2.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar2, gridBagConstraints);

        BtnConsultar2.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar2.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar2.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar2, gridBagConstraints);

        BtnBaja2.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja2.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja2.setText("Dar de Baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja2, gridBagConstraints);

        LblFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliplus.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(LblFoto3, gridBagConstraints);

        BtnAgregar3.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar3.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar3.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar3, gridBagConstraints);

        BtnConsultar3.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar3.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar3.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar3, gridBagConstraints);

        BtnBaja3.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja3.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja3.setText("Dar de Baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja3, gridBagConstraints);

        LblFoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grefusito.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(LblFoto5, gridBagConstraints);

        BtnAgregar5.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar5.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar5.setText("Agregar Producto");
        BtnAgregar5.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar5, gridBagConstraints);

        BtnConsultar5.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar5.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar5.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar5, gridBagConstraints);

        BtnBaja5.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja5.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja5.setText("Dar de Baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(LblFoto7, gridBagConstraints);

        BtnAgregar6.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar6.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar6.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar6, gridBagConstraints);

        BtnConsultar6.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar6.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar6.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar6, gridBagConstraints);

        BtnBaja6.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja6.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja6.setText("Dar de Baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja6, gridBagConstraints);

        LblFoto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hacendado.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(LblFoto6, gridBagConstraints);

        BtnAgregar7.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar7.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar7.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar7, gridBagConstraints);

        BtnConsultar7.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar7.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar7.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar7, gridBagConstraints);

        BtnBaja7.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja7.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja7.setText("Dar de Baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja7, gridBagConstraints);

        LblFoto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blosteverde.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(LblFoto8, gridBagConstraints);

        BtnAgregar8.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar8.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar8.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar8, gridBagConstraints);

        BtnConsultar8.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar8.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar8.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar8, gridBagConstraints);

        BtnBaja8.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja8.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja8.setText("Dar de Baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja8, gridBagConstraints);

        Lblfoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferrero.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(Lblfoto4, gridBagConstraints);

        BtnAgregar4.setBackground(new java.awt.Color(0, 153, 0));
        BtnAgregar4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar4.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar4.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnAgregar4, gridBagConstraints);

        BtnConsultar4.setBackground(new java.awt.Color(0, 0, 204));
        BtnConsultar4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConsultar4.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar4.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnConsultar4, gridBagConstraints);

        BtnBaja4.setBackground(new java.awt.Color(204, 0, 0));
        BtnBaja4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBaja4.setForeground(new java.awt.Color(255, 255, 255));
        BtnBaja4.setText("Dar de Baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(BtnBaja4, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nestle.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(42, 40, 42, 40);
        PnlProveedores.add(jLabel1, gridBagConstraints);

        Pnlinicio.add(PnlProveedores, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnlinicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnlinicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregar1ActionPerformed
        VentanaAsociarProductos conectar_asociarproducto=new VentanaAsociarProductos();
        conectar_asociarproducto.setVisible(true);
    }//GEN-LAST:event_BtnAgregar1ActionPerformed

    private void BtnBaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBaja1ActionPerformed
       String [] opciones={"Eliminar proveedor","Cancelar"};
       int seleccion= JOptionPane.showOptionDialog(this,"¿Esta seguro que desea eliminar este proveedor?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
          PnlProveedores.remove(LblFoto1);
          PnlProveedores.remove(BtnAgregar1);
          PnlProveedores.remove(BtnConsultar1);
          PnlProveedores.remove(BtnBaja1);
          
           
        }
    }//GEN-LAST:event_BtnBaja1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaPrincipalAdministrador volver_admin=new VentanaPrincipalAdministrador();
        volver_admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gestion_proveedores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar1;
    private javax.swing.JButton BtnAgregar2;
    private javax.swing.JButton BtnAgregar3;
    private javax.swing.JButton BtnAgregar4;
    private javax.swing.JButton BtnAgregar5;
    private javax.swing.JButton BtnAgregar6;
    private javax.swing.JButton BtnAgregar7;
    private javax.swing.JButton BtnAgregar8;
    private javax.swing.JButton BtnBaja1;
    private javax.swing.JButton BtnBaja2;
    private javax.swing.JButton BtnBaja3;
    private javax.swing.JButton BtnBaja4;
    private javax.swing.JButton BtnBaja5;
    private javax.swing.JButton BtnBaja6;
    private javax.swing.JButton BtnBaja7;
    private javax.swing.JButton BtnBaja8;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnConsultar1;
    private javax.swing.JButton BtnConsultar2;
    private javax.swing.JButton BtnConsultar3;
    private javax.swing.JButton BtnConsultar4;
    private javax.swing.JButton BtnConsultar5;
    private javax.swing.JButton BtnConsultar6;
    private javax.swing.JButton BtnConsultar7;
    private javax.swing.JButton BtnConsultar8;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JLabel LblFoto1;
    private javax.swing.JLabel LblFoto2;
    private javax.swing.JLabel LblFoto3;
    private javax.swing.JLabel LblFoto5;
    private javax.swing.JLabel LblFoto6;
    private javax.swing.JLabel LblFoto7;
    private javax.swing.JLabel LblFoto8;
    private javax.swing.JLabel LblPerfil;
    private javax.swing.JLabel LblTItulo;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JLabel Lblfoto4;
    private javax.swing.JPanel PnlEncabezado;
    private javax.swing.JPanel PnlProveedores;
    private javax.swing.JPanel PnlUsuario;
    private javax.swing.JPanel Pnlinicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
