/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author MEDAC
 */
public class Gestion_ventas_cajasDiarias extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gestion_ventas_cajasDiarias.class.getName());

    /**
     * Creates new form Gestion_ventas_cajasDiarias
     */
    public Gestion_ventas_cajasDiarias() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        redimensionarIcono(LblFondo, "fondopantallagestionventass.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlInicio = new javax.swing.JPanel();
        PnlFondoPantalla = new javax.swing.JPanel();
        LblFoto = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        PnlFondo = new javax.swing.JPanel();
        LblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlInicio.setBackground(new java.awt.Color(255, 255, 255));
        PnlInicio.setPreferredSize(new java.awt.Dimension(1920, 1080));
        PnlInicio.setLayout(new java.awt.BorderLayout());

        PnlFondoPantalla.setBackground(new java.awt.Color(153, 153, 153));
        PnlFondoPantalla.setPreferredSize(new java.awt.Dimension(813, 65));
        PnlFondoPantalla.setLayout(new java.awt.GridBagLayout());

        LblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PnlFondoPantalla.add(LblFoto, gridBagConstraints);

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("GESTIÓN DE VENTAS Y CAJAS DIARIAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        PnlFondoPantalla.add(LblTitulo, gridBagConstraints);

        PnlInicio.add(PnlFondoPantalla, java.awt.BorderLayout.PAGE_START);

        PnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondopantallagestionventass (1).png"))); // NOI18N
        LblFondo.setToolTipText("");
        PnlFondo.add(LblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 773));

        PnlInicio.add(PnlFondo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void redimensionarIconosMenu() {
        redimensionarIcono(LblFondo, "fondopantallagestionventass.png");     
    }
        private void redimensionarIcono(JLabel Lbl, String nombre) {
        ImageIcon icono = new ImageIcon(getClass().getResource("/" + nombre));
        Image imagen = icono.getImage().getScaledInstance(PnlInicio.getHeight(), PnlInicio.getWidth(), Image.SCALE_SMOOTH);
        Lbl.setIcon(new ImageIcon(imagen));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gestion_ventas_cajasDiarias().setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblFondo;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JPanel PnlFondoPantalla;
    private javax.swing.JPanel PnlInicio;
    // End of variables declaration//GEN-END:variables
}
