/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Darío
 */
public class Lista_Pedidos_Proveedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lista_Pedidos_Proveedores.class.getName());

    /**
     * Creates new form Lista_Pedidos_Proveedores
     */
    public Lista_Pedidos_Proveedores() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        PnlMenu.getVerticalScrollBar().setPreferredSize(new Dimension(50,0));
        PnlMenu.getVerticalScrollBar().setUnitIncrement(35);
        //NIVEL RIESGO 2
        if(LblNivel_Riesgo2.getText().equals("Nivel_Riesgo")){
                LblFoto_Riesgo2.setIcon(new ImageIcon(getClass().getResource("/riesgobajo.jpg")));
                LblFoto_Riesgo2.setText(" ");
        }else if(LblNivel_Riesgo2.getText().equals("25")){
             LblFoto_Riesgo2.setIcon(new ImageIcon(getClass().getResource("/riesgomedio.jpg")));
                LblFoto_Riesgo2.setText(" ");
        }else if(LblNivel_Riesgo2.getText().equals("5")){
             LblFoto_Riesgo2.setIcon(new ImageIcon(getClass().getResource("/riesgopeligro.jpg")));
                LblFoto_Riesgo2.setText(" ");
        }
        
        
         //NIVEL RIESGO 2
        if(LblNivel_Riesgo1.getText().equals("Nivel_Riesgo")){
                LblFoto_Riesgo1.setIcon(new ImageIcon(getClass().getResource("/riesgobajo.jpg")));
                LblFoto_Riesgo1.setText(" ");
        }else if(LblNivel_Riesgo1.getText().equals("25")){
             LblFoto_Riesgo1.setIcon(new ImageIcon(getClass().getResource("/riesgomedio.jpg")));
                LblFoto_Riesgo1.setText(" ");
        }else if(LblNivel_Riesgo1.getText().equals("5")){
             LblFoto_Riesgo1.setIcon(new ImageIcon(getClass().getResource("/riesgopeligro.jpg")));
                LblFoto_Riesgo1.setText(" ");
        }
        
        //AQUI FALTARIA CMABIAR LOS GET TEXT EQUALS A NIVEL DEL RIESGO DE STOCK DELA VARIABLE QUE PASARA POR PANTALLA DE LAS UNIDADES DEL PRODUCTO 
        //ADEMAS DE EL NOMBRE PROVVEDOR, DEL PRODUCTO Y SU PRECIO QUE LO TIENE QUE PASAR EN PANTALLA

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlInicio = new javax.swing.JPanel();
        PnlEncabezado = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblMinifoto = new javax.swing.JLabel();
        PnlPie = new javax.swing.JPanel();
        LblMiniLogo = new javax.swing.JLabel();
        LblDerechos = new javax.swing.JLabel();
        LblCopy = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(70, 50), new java.awt.Dimension(32767, 0));
        BtnConfirmarPedido = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(32767, 0));
        JlabelMinilogo = new javax.swing.JLabel();
        LbTitulito = new javax.swing.JLabel();
        LblProductos_Total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PnlMenu = new javax.swing.JScrollPane();
        Pnlmenucito = new javax.swing.JPanel();
        PnlProveedor1 = new javax.swing.JPanel();
        LblFoto1 = new javax.swing.JLabel();
        LblNombreProducto1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PnlCuadro = new javax.swing.JPanel();
        LblTitulo1 = new javax.swing.JLabel();
        LblProveedor1 = new javax.swing.JLabel();
        LblTituloStock1 = new javax.swing.JLabel();
        LblNivel_Riesgo1 = new javax.swing.JLabel();
        LblFoto_Riesgo1 = new javax.swing.JLabel();
        BtnModificar_Pedido1 = new javax.swing.JButton();
        IncrementoProducto1 = new javax.swing.JLabel();
        BotonAgregar1 = new javax.swing.JButton();
        BotonRestar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PnlCuadro1 = new javax.swing.JPanel();
        LblTituloSuministrado1 = new javax.swing.JLabel();
        LblNombreProveedor1 = new javax.swing.JLabel();
        Lblproveedor1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PnlProveedor2 = new javax.swing.JPanel();
        LblFoto2 = new javax.swing.JLabel();
        LblNombreProducto2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PnlCuadro2 = new javax.swing.JPanel();
        LblTitulo2 = new javax.swing.JLabel();
        LblProveedor2 = new javax.swing.JLabel();
        LblTituloStock2 = new javax.swing.JLabel();
        LblNivel_Riesgo2 = new javax.swing.JLabel();
        LblFoto_Riesgo2 = new javax.swing.JLabel();
        BtnModificar_Pedido2 = new javax.swing.JButton();
        IncrementoProducto2 = new javax.swing.JLabel();
        BotonAgregar2 = new javax.swing.JButton();
        BotonRestar2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        PnlCuadro3 = new javax.swing.JPanel();
        LblTituloSuministrado2 = new javax.swing.JLabel();
        LblNombreProveedor2 = new javax.swing.JLabel();
        Lblproveedor2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PnlProveedor3 = new javax.swing.JPanel();
        LblFoto3 = new javax.swing.JLabel();
        LblNombreProducto3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PnlCuadro4 = new javax.swing.JPanel();
        LblTitulo3 = new javax.swing.JLabel();
        LblProveedor3 = new javax.swing.JLabel();
        LblTituloStock3 = new javax.swing.JLabel();
        LblNivel_Riesgo3 = new javax.swing.JLabel();
        LblFoto_Riesgo3 = new javax.swing.JLabel();
        BtnModificar_Pedido3 = new javax.swing.JButton();
        IncrementoProductio3 = new javax.swing.JLabel();
        BotonAgregar3 = new javax.swing.JButton();
        BotonRestar3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        PnlCuadro5 = new javax.swing.JPanel();
        LblTituloSuministrado3 = new javax.swing.JLabel();
        LblNombreProveedor3 = new javax.swing.JLabel();
        Lblproveedor3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PnlProveedor4 = new javax.swing.JPanel();
        LblFoto4 = new javax.swing.JLabel();
        LblNombreProducto4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PnlCuadro6 = new javax.swing.JPanel();
        LblTitulo4 = new javax.swing.JLabel();
        LblProveedor4 = new javax.swing.JLabel();
        LblTituloStock4 = new javax.swing.JLabel();
        LblNivel_Riesgo4 = new javax.swing.JLabel();
        LblFoto_Riesgo4 = new javax.swing.JLabel();
        BtnModificar_Pedido4 = new javax.swing.JButton();
        IncrementoProducto4 = new javax.swing.JLabel();
        BotonAgregar4 = new javax.swing.JButton();
        BotonRestar4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        PnlCuadro7 = new javax.swing.JPanel();
        LblTituloSuministrado4 = new javax.swing.JLabel();
        LblNombreProveedor4 = new javax.swing.JLabel();
        Lblproveedor4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        PnlProveedor5 = new javax.swing.JPanel();
        LblFoto5 = new javax.swing.JLabel();
        LblNombreProducto5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PnlCuadro8 = new javax.swing.JPanel();
        LblTitulo5 = new javax.swing.JLabel();
        LblProveedor5 = new javax.swing.JLabel();
        LblTituloStock5 = new javax.swing.JLabel();
        LblNivel_Riesgo5 = new javax.swing.JLabel();
        LblFoto_Riesgo5 = new javax.swing.JLabel();
        BtnModificar_Pedido5 = new javax.swing.JButton();
        IncrementoProducto5 = new javax.swing.JLabel();
        BotonAgregar5 = new javax.swing.JButton();
        BotonRestar5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        PnlCuadro9 = new javax.swing.JPanel();
        LblTituloSuministrado5 = new javax.swing.JLabel();
        LblNombreProveedor5 = new javax.swing.JLabel();
        Lblproveedor5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        PnlProveedor6 = new javax.swing.JPanel();
        LblFoto6 = new javax.swing.JLabel();
        LblNombreProducto6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PnlCuadro10 = new javax.swing.JPanel();
        LblTitulo6 = new javax.swing.JLabel();
        LblProveedor6 = new javax.swing.JLabel();
        LblTituloStock6 = new javax.swing.JLabel();
        LblNivel_Riesgo6 = new javax.swing.JLabel();
        LblFoto_Riesgo6 = new javax.swing.JLabel();
        BtnModificar_Pedido6 = new javax.swing.JButton();
        IncrementoProducto6 = new javax.swing.JLabel();
        BotonAgregar6 = new javax.swing.JButton();
        BotonRestar6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        PnlCuadro11 = new javax.swing.JPanel();
        LblTituloSuministrado6 = new javax.swing.JLabel();
        LblNombreProveedor6 = new javax.swing.JLabel();
        Lblproveedor6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlInicio.setBackground(new java.awt.Color(255, 255, 255));
        PnlInicio.setLayout(new java.awt.BorderLayout());

        PnlEncabezado.setBackground(new java.awt.Color(102, 102, 102));
        PnlEncabezado.setLayout(new java.awt.GridBagLayout());

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("LISTA DE PEDIDOS A PROVEEDORES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        PnlEncabezado.add(LblTitulo, gridBagConstraints);

        LblMinifoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 9, 0);
        PnlEncabezado.add(LblMinifoto, gridBagConstraints);

        PnlInicio.add(PnlEncabezado, java.awt.BorderLayout.PAGE_START);

        PnlPie.setBackground(new java.awt.Color(204, 204, 204));
        PnlPie.setLayout(new java.awt.GridBagLayout());

        LblMiniLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        PnlPie.add(LblMiniLogo, new java.awt.GridBagConstraints());

        LblDerechos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblDerechos.setForeground(new java.awt.Color(0, 0, 0));
        LblDerechos.setText("Todos los derechos reservados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        PnlPie.add(LblDerechos, gridBagConstraints);

        LblCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copyright.png"))); // NOI18N
        PnlPie.add(LblCopy, new java.awt.GridBagConstraints());
        PnlPie.add(filler1, new java.awt.GridBagConstraints());

        BtnConfirmarPedido.setBackground(new java.awt.Color(0, 204, 0));
        BtnConfirmarPedido.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        BtnConfirmarPedido.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmarPedido.setText("CONFIRMAR PEDIDO(SOLO ADMIN)");
        BtnConfirmarPedido.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        PnlPie.add(BtnConfirmarPedido, gridBagConstraints);
        PnlPie.add(filler2, new java.awt.GridBagConstraints());

        JlabelMinilogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logitoinformacion.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        PnlPie.add(JlabelMinilogo, gridBagConstraints);

        LbTitulito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbTitulito.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulito.setText("Productos Totales Vendidos:");
        PnlPie.add(LbTitulito, new java.awt.GridBagConstraints());

        LblProductos_Total.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblProductos_Total.setForeground(new java.awt.Color(0, 0, 0));
        LblProductos_Total.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        PnlPie.add(LblProductos_Total, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIDA");
        jButton1.setPreferredSize(new java.awt.Dimension(176, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        PnlPie.add(jButton1, gridBagConstraints);

        PnlInicio.add(PnlPie, java.awt.BorderLayout.PAGE_END);

        PnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        Pnlmenucito.setBackground(new java.awt.Color(255, 255, 255));
        Pnlmenucito.setLayout(new java.awt.GridLayout(99, 1, 5, 0));

        PnlProveedor1.setBackground(new java.awt.Color(0, 255, 204));
        PnlProveedor1.setPreferredSize(new java.awt.Dimension(2400, 404));
        PnlProveedor1.setLayout(new java.awt.GridBagLayout());

        LblFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asturiana.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(LblFoto1, gridBagConstraints);

        LblNombreProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNombreProducto1.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProducto1.setText("Leche Asturiana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(LblNombreProducto1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("20,99 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(jLabel3, gridBagConstraints);

        PnlCuadro.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro.setMinimumSize(new java.awt.Dimension(500, 100));
        PnlCuadro.setLayout(new java.awt.GridBagLayout());

        LblTitulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo1.setText("Peticion enviada por:");
        PnlCuadro.add(LblTitulo1, new java.awt.GridBagConstraints());

        LblProveedor1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblProveedor1.setForeground(new java.awt.Color(0, 0, 0));
        LblProveedor1.setText("Nombre_Proveedor");
        PnlCuadro.add(LblProveedor1, new java.awt.GridBagConstraints());

        LblTituloStock1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloStock1.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloStock1.setText("Estado de stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro.add(LblTituloStock1, gridBagConstraints);

        LblNivel_Riesgo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblNivel_Riesgo1.setForeground(new java.awt.Color(0, 0, 0));
        LblNivel_Riesgo1.setText("Nivel_Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCuadro.add(LblNivel_Riesgo1, gridBagConstraints);

        LblFoto_Riesgo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFoto_Riesgo1.setForeground(new java.awt.Color(0, 0, 0));
        LblFoto_Riesgo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/riesgobajo.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro.add(LblFoto_Riesgo1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(PnlCuadro, gridBagConstraints);

        BtnModificar_Pedido1.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar_Pedido1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnModificar_Pedido1.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar_Pedido1.setText("MODIFICAR PEDIDO");
        BtnModificar_Pedido1.setPreferredSize(new java.awt.Dimension(300, 27));
        BtnModificar_Pedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificar_Pedido1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(BtnModificar_Pedido1, gridBagConstraints);

        IncrementoProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncrementoProducto1.setForeground(new java.awt.Color(0, 0, 0));
        IncrementoProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoproducto.png"))); // NOI18N
        IncrementoProducto1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(IncrementoProducto1, gridBagConstraints);

        BotonAgregar1.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregar1.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregar1.setText("+");
        BotonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(BotonAgregar1, gridBagConstraints);

        BotonRestar1.setBackground(new java.awt.Color(255, 0, 51));
        BotonRestar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonRestar1.setForeground(new java.awt.Color(0, 0, 0));
        BotonRestar1.setText("-");
        BotonRestar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(BotonRestar1, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(jLabel5, gridBagConstraints);

        PnlCuadro1.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro1.setMinimumSize(new java.awt.Dimension(400, 100));
        PnlCuadro1.setLayout(new java.awt.GridBagLayout());

        LblTituloSuministrado1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloSuministrado1.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloSuministrado1.setText("Suministrado por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro1.add(LblTituloSuministrado1, gridBagConstraints);

        LblNombreProveedor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNombreProveedor1.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProveedor1.setText("Nombre_Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro1.add(LblNombreProveedor1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(PnlCuadro1, gridBagConstraints);

        Lblproveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hacendado.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 50);
        PnlProveedor1.add(Lblproveedor1, gridBagConstraints);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PnlProveedor1.add(jPanel1, gridBagConstraints);

        Pnlmenucito.add(PnlProveedor1);

        PnlProveedor2.setBackground(new java.awt.Color(0, 255, 204));
        PnlProveedor2.setPreferredSize(new java.awt.Dimension(2400, 404));
        PnlProveedor2.setLayout(new java.awt.GridBagLayout());

        LblFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/choco.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(LblFoto2, gridBagConstraints);

        LblNombreProducto2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNombreProducto2.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProducto2.setText("Choco Flakes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(LblNombreProducto2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("8,99");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(jLabel4, gridBagConstraints);

        PnlCuadro2.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro2.setMinimumSize(new java.awt.Dimension(500, 100));
        PnlCuadro2.setLayout(new java.awt.GridBagLayout());

        LblTitulo2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo2.setText("Peticion enviada por:");
        PnlCuadro2.add(LblTitulo2, new java.awt.GridBagConstraints());

        LblProveedor2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblProveedor2.setForeground(new java.awt.Color(0, 0, 0));
        LblProveedor2.setText("Nombre_Proveedor");
        PnlCuadro2.add(LblProveedor2, new java.awt.GridBagConstraints());

        LblTituloStock2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloStock2.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloStock2.setText("Estado de stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro2.add(LblTituloStock2, gridBagConstraints);

        LblNivel_Riesgo2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblNivel_Riesgo2.setForeground(new java.awt.Color(0, 0, 0));
        LblNivel_Riesgo2.setText("Nivel_Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCuadro2.add(LblNivel_Riesgo2, gridBagConstraints);

        LblFoto_Riesgo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFoto_Riesgo2.setForeground(new java.awt.Color(0, 0, 0));
        LblFoto_Riesgo2.setText("Foto_Nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro2.add(LblFoto_Riesgo2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(PnlCuadro2, gridBagConstraints);

        BtnModificar_Pedido2.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar_Pedido2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnModificar_Pedido2.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar_Pedido2.setText("MODIFICAR PEDIDO");
        BtnModificar_Pedido2.setPreferredSize(new java.awt.Dimension(300, 27));
        BtnModificar_Pedido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificar_Pedido2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(BtnModificar_Pedido2, gridBagConstraints);

        IncrementoProducto2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncrementoProducto2.setForeground(new java.awt.Color(0, 0, 0));
        IncrementoProducto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoproducto.png"))); // NOI18N
        IncrementoProducto2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(IncrementoProducto2, gridBagConstraints);

        BotonAgregar2.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregar2.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregar2.setText("+");
        BotonAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(BotonAgregar2, gridBagConstraints);

        BotonRestar2.setBackground(new java.awt.Color(255, 0, 51));
        BotonRestar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonRestar2.setForeground(new java.awt.Color(0, 0, 0));
        BotonRestar2.setText("-");
        BotonRestar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestar2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(BotonRestar2, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(jLabel7, gridBagConstraints);

        PnlCuadro3.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro3.setMinimumSize(new java.awt.Dimension(400, 100));
        PnlCuadro3.setLayout(new java.awt.GridBagLayout());

        LblTituloSuministrado2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloSuministrado2.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloSuministrado2.setText("Suministrado por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro3.add(LblTituloSuministrado2, gridBagConstraints);

        LblNombreProveedor2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNombreProveedor2.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProveedor2.setText("Nombre_Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro3.add(LblNombreProveedor2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor2.add(PnlCuadro3, gridBagConstraints);

        Lblproveedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuetara.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 50);
        PnlProveedor2.add(Lblproveedor2, gridBagConstraints);

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PnlProveedor2.add(jPanel2, gridBagConstraints);

        Pnlmenucito.add(PnlProveedor2);

        PnlProveedor3.setBackground(new java.awt.Color(0, 255, 204));
        PnlProveedor3.setPreferredSize(new java.awt.Dimension(2400, 404));
        PnlProveedor3.setLayout(new java.awt.GridBagLayout());

        LblFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gofre.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(LblFoto3, gridBagConstraints);

        LblNombreProducto3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNombreProducto3.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProducto3.setText("Gofres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(LblNombreProducto3, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("5,70");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(jLabel8, gridBagConstraints);

        PnlCuadro4.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro4.setMinimumSize(new java.awt.Dimension(500, 100));
        PnlCuadro4.setLayout(new java.awt.GridBagLayout());

        LblTitulo3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTitulo3.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo3.setText("Peticion enviada por:");
        PnlCuadro4.add(LblTitulo3, new java.awt.GridBagConstraints());

        LblProveedor3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblProveedor3.setForeground(new java.awt.Color(0, 0, 0));
        LblProveedor3.setText("Nombre_Proveedor");
        PnlCuadro4.add(LblProveedor3, new java.awt.GridBagConstraints());

        LblTituloStock3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloStock3.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloStock3.setText("Estado de stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro4.add(LblTituloStock3, gridBagConstraints);

        LblNivel_Riesgo3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblNivel_Riesgo3.setForeground(new java.awt.Color(0, 0, 0));
        LblNivel_Riesgo3.setText("Nivel_Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCuadro4.add(LblNivel_Riesgo3, gridBagConstraints);

        LblFoto_Riesgo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFoto_Riesgo3.setForeground(new java.awt.Color(0, 0, 0));
        LblFoto_Riesgo3.setText("Foto_Nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro4.add(LblFoto_Riesgo3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(PnlCuadro4, gridBagConstraints);

        BtnModificar_Pedido3.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar_Pedido3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnModificar_Pedido3.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar_Pedido3.setText("MODIFICAR PEDIDO");
        BtnModificar_Pedido3.setPreferredSize(new java.awt.Dimension(300, 27));
        BtnModificar_Pedido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificar_Pedido3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(BtnModificar_Pedido3, gridBagConstraints);

        IncrementoProductio3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncrementoProductio3.setForeground(new java.awt.Color(0, 0, 0));
        IncrementoProductio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoproducto.png"))); // NOI18N
        IncrementoProductio3.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(IncrementoProductio3, gridBagConstraints);

        BotonAgregar3.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregar3.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregar3.setText("+");
        BotonAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(BotonAgregar3, gridBagConstraints);

        BotonRestar3.setBackground(new java.awt.Color(255, 0, 51));
        BotonRestar3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonRestar3.setForeground(new java.awt.Color(0, 0, 0));
        BotonRestar3.setText("-");
        BotonRestar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestar3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(BotonRestar3, gridBagConstraints);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(jLabel10, gridBagConstraints);

        PnlCuadro5.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro5.setMinimumSize(new java.awt.Dimension(400, 100));
        PnlCuadro5.setLayout(new java.awt.GridBagLayout());

        LblTituloSuministrado3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloSuministrado3.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloSuministrado3.setText("Suministrado por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro5.add(LblTituloSuministrado3, gridBagConstraints);

        LblNombreProveedor3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNombreProveedor3.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProveedor3.setText("Nombre_Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro5.add(LblNombreProveedor3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor3.add(PnlCuadro5, gridBagConstraints);

        Lblproveedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hacendado.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 50);
        PnlProveedor3.add(Lblproveedor3, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PnlProveedor3.add(jPanel3, gridBagConstraints);

        Pnlmenucito.add(PnlProveedor3);

        PnlProveedor4.setBackground(new java.awt.Color(0, 255, 204));
        PnlProveedor4.setPreferredSize(new java.awt.Dimension(2400, 404));
        PnlProveedor4.setLayout(new java.awt.GridBagLayout());

        LblFoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donut.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(LblFoto4, gridBagConstraints);

        LblNombreProducto4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNombreProducto4.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProducto4.setText("Donuts sabor Chocolate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(LblNombreProducto4, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("3,99 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(jLabel11, gridBagConstraints);

        PnlCuadro6.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro6.setMinimumSize(new java.awt.Dimension(500, 100));
        PnlCuadro6.setLayout(new java.awt.GridBagLayout());

        LblTitulo4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTitulo4.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo4.setText("Peticion enviada por:");
        PnlCuadro6.add(LblTitulo4, new java.awt.GridBagConstraints());

        LblProveedor4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblProveedor4.setForeground(new java.awt.Color(0, 0, 0));
        LblProveedor4.setText("Nombre_Proveedor");
        PnlCuadro6.add(LblProveedor4, new java.awt.GridBagConstraints());

        LblTituloStock4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloStock4.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloStock4.setText("Estado de stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro6.add(LblTituloStock4, gridBagConstraints);

        LblNivel_Riesgo4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblNivel_Riesgo4.setForeground(new java.awt.Color(0, 0, 0));
        LblNivel_Riesgo4.setText("Nivel_Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCuadro6.add(LblNivel_Riesgo4, gridBagConstraints);

        LblFoto_Riesgo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFoto_Riesgo4.setForeground(new java.awt.Color(0, 0, 0));
        LblFoto_Riesgo4.setText("Foto_Nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro6.add(LblFoto_Riesgo4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(PnlCuadro6, gridBagConstraints);

        BtnModificar_Pedido4.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar_Pedido4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnModificar_Pedido4.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar_Pedido4.setText("MODIFICAR PEDIDO");
        BtnModificar_Pedido4.setPreferredSize(new java.awt.Dimension(300, 27));
        BtnModificar_Pedido4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificar_Pedido4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(BtnModificar_Pedido4, gridBagConstraints);

        IncrementoProducto4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncrementoProducto4.setForeground(new java.awt.Color(0, 0, 0));
        IncrementoProducto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoproducto.png"))); // NOI18N
        IncrementoProducto4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(IncrementoProducto4, gridBagConstraints);

        BotonAgregar4.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregar4.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregar4.setText("+");
        BotonAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(BotonAgregar4, gridBagConstraints);

        BotonRestar4.setBackground(new java.awt.Color(255, 0, 51));
        BotonRestar4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonRestar4.setForeground(new java.awt.Color(0, 0, 0));
        BotonRestar4.setText("-");
        BotonRestar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestar4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(BotonRestar4, gridBagConstraints);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(jLabel13, gridBagConstraints);

        PnlCuadro7.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro7.setMinimumSize(new java.awt.Dimension(400, 100));
        PnlCuadro7.setLayout(new java.awt.GridBagLayout());

        LblTituloSuministrado4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloSuministrado4.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloSuministrado4.setText("Suministrado por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro7.add(LblTituloSuministrado4, gridBagConstraints);

        LblNombreProveedor4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNombreProveedor4.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProveedor4.setText("Nombre_Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro7.add(LblNombreProveedor4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor4.add(PnlCuadro7, gridBagConstraints);

        Lblproveedor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hacendado.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 50);
        PnlProveedor4.add(Lblproveedor4, gridBagConstraints);

        jPanel4.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PnlProveedor4.add(jPanel4, gridBagConstraints);

        Pnlmenucito.add(PnlProveedor4);

        PnlProveedor5.setBackground(new java.awt.Color(0, 255, 204));
        PnlProveedor5.setPreferredSize(new java.awt.Dimension(2400, 404));
        PnlProveedor5.setLayout(new java.awt.GridBagLayout());

        LblFoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ladron.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(LblFoto5, gridBagConstraints);

        LblNombreProducto5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNombreProducto5.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProducto5.setText("Ferrero Robé");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(LblNombreProducto5, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("10,20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(jLabel14, gridBagConstraints);

        PnlCuadro8.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro8.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro8.setMinimumSize(new java.awt.Dimension(500, 100));
        PnlCuadro8.setLayout(new java.awt.GridBagLayout());

        LblTitulo5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTitulo5.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo5.setText("Peticion enviada por:");
        PnlCuadro8.add(LblTitulo5, new java.awt.GridBagConstraints());

        LblProveedor5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblProveedor5.setForeground(new java.awt.Color(0, 0, 0));
        LblProveedor5.setText("Nombre_Proveedor");
        PnlCuadro8.add(LblProveedor5, new java.awt.GridBagConstraints());

        LblTituloStock5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloStock5.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloStock5.setText("Estado de stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro8.add(LblTituloStock5, gridBagConstraints);

        LblNivel_Riesgo5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblNivel_Riesgo5.setForeground(new java.awt.Color(0, 0, 0));
        LblNivel_Riesgo5.setText("Nivel_Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCuadro8.add(LblNivel_Riesgo5, gridBagConstraints);

        LblFoto_Riesgo5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFoto_Riesgo5.setForeground(new java.awt.Color(0, 0, 0));
        LblFoto_Riesgo5.setText("Foto_Nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro8.add(LblFoto_Riesgo5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(PnlCuadro8, gridBagConstraints);

        BtnModificar_Pedido5.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar_Pedido5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnModificar_Pedido5.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar_Pedido5.setText("MODIFICAR PEDIDO");
        BtnModificar_Pedido5.setPreferredSize(new java.awt.Dimension(300, 27));
        BtnModificar_Pedido5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificar_Pedido5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(BtnModificar_Pedido5, gridBagConstraints);

        IncrementoProducto5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncrementoProducto5.setForeground(new java.awt.Color(0, 0, 0));
        IncrementoProducto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoproducto.png"))); // NOI18N
        IncrementoProducto5.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(IncrementoProducto5, gridBagConstraints);

        BotonAgregar5.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregar5.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregar5.setText("+");
        BotonAgregar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(BotonAgregar5, gridBagConstraints);

        BotonRestar5.setBackground(new java.awt.Color(255, 0, 51));
        BotonRestar5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonRestar5.setForeground(new java.awt.Color(0, 0, 0));
        BotonRestar5.setText("-");
        BotonRestar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestar5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(BotonRestar5, gridBagConstraints);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(jLabel16, gridBagConstraints);

        PnlCuadro9.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro9.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro9.setMinimumSize(new java.awt.Dimension(400, 100));
        PnlCuadro9.setLayout(new java.awt.GridBagLayout());

        LblTituloSuministrado5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloSuministrado5.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloSuministrado5.setText("Suministrado por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro9.add(LblTituloSuministrado5, gridBagConstraints);

        LblNombreProveedor5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNombreProveedor5.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProveedor5.setText("Nombre_Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro9.add(LblNombreProveedor5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor5.add(PnlCuadro9, gridBagConstraints);

        Lblproveedor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferrero.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 50);
        PnlProveedor5.add(Lblproveedor5, gridBagConstraints);

        jPanel5.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PnlProveedor5.add(jPanel5, gridBagConstraints);

        Pnlmenucito.add(PnlProveedor5);

        PnlProveedor6.setBackground(new java.awt.Color(0, 255, 204));
        PnlProveedor6.setPreferredSize(new java.awt.Dimension(2400, 404));
        PnlProveedor6.setLayout(new java.awt.GridBagLayout());

        LblFoto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloste.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(LblFoto6, gridBagConstraints);

        LblNombreProducto6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNombreProducto6.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProducto6.setText("Bloste");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(LblNombreProducto6, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("100,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(jLabel17, gridBagConstraints);

        PnlCuadro10.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro10.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro10.setMinimumSize(new java.awt.Dimension(500, 100));
        PnlCuadro10.setLayout(new java.awt.GridBagLayout());

        LblTitulo6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTitulo6.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo6.setText("Peticion enviada por:");
        PnlCuadro10.add(LblTitulo6, new java.awt.GridBagConstraints());

        LblProveedor6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblProveedor6.setForeground(new java.awt.Color(0, 0, 0));
        LblProveedor6.setText("Nombre_Proveedor");
        PnlCuadro10.add(LblProveedor6, new java.awt.GridBagConstraints());

        LblTituloStock6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloStock6.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloStock6.setText("Estado de stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro10.add(LblTituloStock6, gridBagConstraints);

        LblNivel_Riesgo6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblNivel_Riesgo6.setForeground(new java.awt.Color(0, 0, 0));
        LblNivel_Riesgo6.setText("Nivel_Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCuadro10.add(LblNivel_Riesgo6, gridBagConstraints);

        LblFoto_Riesgo6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFoto_Riesgo6.setForeground(new java.awt.Color(0, 0, 0));
        LblFoto_Riesgo6.setText("Foto_Nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro10.add(LblFoto_Riesgo6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(PnlCuadro10, gridBagConstraints);

        BtnModificar_Pedido6.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar_Pedido6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnModificar_Pedido6.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar_Pedido6.setText("MODIFICAR PEDIDO");
        BtnModificar_Pedido6.setPreferredSize(new java.awt.Dimension(300, 27));
        BtnModificar_Pedido6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificar_Pedido6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(BtnModificar_Pedido6, gridBagConstraints);

        IncrementoProducto6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncrementoProducto6.setForeground(new java.awt.Color(0, 0, 0));
        IncrementoProducto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoproducto.png"))); // NOI18N
        IncrementoProducto6.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(IncrementoProducto6, gridBagConstraints);

        BotonAgregar6.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregar6.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregar6.setText("+");
        BotonAgregar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(BotonAgregar6, gridBagConstraints);

        BotonRestar6.setBackground(new java.awt.Color(255, 0, 51));
        BotonRestar6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonRestar6.setForeground(new java.awt.Color(0, 0, 0));
        BotonRestar6.setText("-");
        BotonRestar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestar6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(BotonRestar6, gridBagConstraints);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(jLabel19, gridBagConstraints);

        PnlCuadro11.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.white), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5)));
        PnlCuadro11.setMinimumSize(new java.awt.Dimension(400, 100));
        PnlCuadro11.setLayout(new java.awt.GridBagLayout());

        LblTituloSuministrado6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloSuministrado6.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloSuministrado6.setText("Suministrado por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro11.add(LblTituloSuministrado6, gridBagConstraints);

        LblNombreProveedor6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNombreProveedor6.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProveedor6.setText("Nombre_Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro11.add(LblNombreProveedor6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor6.add(PnlCuadro11, gridBagConstraints);

        Lblproveedor6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blosteverde.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 50);
        PnlProveedor6.add(Lblproveedor6, gridBagConstraints);

        jPanel6.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PnlProveedor6.add(jPanel6, gridBagConstraints);

        Pnlmenucito.add(PnlProveedor6);

        PnlMenu.setViewportView(Pnlmenucito);

        PnlInicio.add(PnlMenu, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 2168, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 2743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    private void BotonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar1ActionPerformed
     int incremento1;
     incremento1=Integer.parseInt(IncrementoProducto1.getText());
     incremento1++;
     cantidad_total_sumar(incremento1);
     String resultado1= Integer.toString(incremento1);
     IncrementoProducto1.setText(resultado1);
     
    }//GEN-LAST:event_BotonAgregar1ActionPerformed

    private void BotonRestar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestar1ActionPerformed
    if(IncrementoProducto1.getText().equals("0")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    else{
        int incremento1;
        incremento1=Integer.parseInt(IncrementoProducto1.getText());
        incremento1--;
        cantidad_total_restar(incremento1);
        String resultado1= Integer.toString(incremento1);
        IncrementoProducto1.setText(resultado1);
    }
        
     
     
    }//GEN-LAST:event_BotonRestar1ActionPerformed

    private void BotonRestar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestar2ActionPerformed
    
       if(IncrementoProducto2.getText().equals("0")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    else{
        int incremento2;
        incremento2=Integer.parseInt(IncrementoProducto2.getText());
        incremento2--;
        cantidad_total_restar(incremento2);
        String resultado= Integer.toString(incremento2);
        IncrementoProducto2.setText(resultado);
    }
    }//GEN-LAST:event_BotonRestar2ActionPerformed

    private void BotonAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar2ActionPerformed
           int incremento2;
     incremento2=Integer.parseInt(IncrementoProducto2.getText());
     incremento2++;
     cantidad_total_sumar(incremento2);
     String resultado= Integer.toString(incremento2);
     IncrementoProducto2.setText(resultado);
     if(IncrementoProducto2.getText().equals("-1")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    }//GEN-LAST:event_BotonAgregar2ActionPerformed

    private void BotonAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar3ActionPerformed
           int incremento3;
     incremento3=Integer.parseInt(IncrementoProductio3.getText());
     incremento3++;
     cantidad_total_sumar(incremento3);
     String resultado3= Integer.toString(incremento3);
     IncrementoProductio3.setText(resultado3);
     if(IncrementoProductio3.getText().equals("-1")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    }//GEN-LAST:event_BotonAgregar3ActionPerformed

    private void BotonRestar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestar3ActionPerformed
       if(IncrementoProductio3.getText().equals("0")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    else{
        int incremento3;
        incremento3=Integer.parseInt(IncrementoProductio3.getText());
        incremento3--;
        cantidad_total_restar(incremento3);
        String resultado= Integer.toString(incremento3);
        IncrementoProductio3.setText(resultado);
    }
    }//GEN-LAST:event_BotonRestar3ActionPerformed

    private void BotonAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar4ActionPerformed
           int incremento4;
     incremento4=Integer.parseInt(IncrementoProducto4.getText());
     incremento4++;
     cantidad_total_sumar(incremento4);
     String resultado4= Integer.toString(incremento4);
     IncrementoProducto4.setText(resultado4);
     if(IncrementoProducto4.getText().equals("-1")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    }//GEN-LAST:event_BotonAgregar4ActionPerformed

    private void BotonRestar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestar4ActionPerformed
       if(IncrementoProducto4.getText().equals("0")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    else{
        int incremento4;
        incremento4=Integer.parseInt(IncrementoProducto4.getText());
        incremento4--;
        cantidad_total_restar(incremento4);
        String resultado= Integer.toString(incremento4);
        IncrementoProducto2.setText(resultado);
    }
    }//GEN-LAST:event_BotonRestar4ActionPerformed

    private void BotonAgregar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar5ActionPerformed
          int incremento5;
     incremento5=Integer.parseInt(IncrementoProducto5.getText());
     incremento5++;
cantidad_total_sumar(incremento5);
     String resultado5= Integer.toString(incremento5);
     IncrementoProducto5.setText(resultado5);
     if(IncrementoProducto5.getText().equals("-1")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    }//GEN-LAST:event_BotonAgregar5ActionPerformed

    private void BotonRestar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestar5ActionPerformed
         if(IncrementoProducto5.getText().equals("0")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    else{
        int incremento5;
        incremento5=Integer.parseInt(IncrementoProducto5.getText());
        incremento5--;
        cantidad_total_restar(incremento5);
        String resultado= Integer.toString(incremento5);
        IncrementoProducto5.setText(resultado);
    }
    }//GEN-LAST:event_BotonRestar5ActionPerformed

    private void BotonAgregar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar6ActionPerformed
           int incremento6;
     incremento6=Integer.parseInt(IncrementoProducto6.getText());
     incremento6++;
     cantidad_total_sumar(incremento6);
     String resultado6= Integer.toString(incremento6);
     IncrementoProducto6.setText(resultado6);
     if(IncrementoProducto6.getText().equals("-1")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    }//GEN-LAST:event_BotonAgregar6ActionPerformed

    private void BotonRestar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestar6ActionPerformed
        if(IncrementoProducto6.getText().equals("0")){
         JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
     }
    else{
        int incremento6;
        incremento6=Integer.parseInt(IncrementoProducto6.getText());
        incremento6--;
        cantidad_total_restar(incremento6);
        String resultado= Integer.toString(incremento6);
        IncrementoProducto2.setText(resultado);
    }
    }//GEN-LAST:event_BotonRestar6ActionPerformed

    private void BtnModificar_Pedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificar_Pedido1ActionPerformed
String [] opciones={"Eliminar peticion producto","Cancelar"};
       int seleccion= JOptionPane.showOptionDialog(this,"¿Qué desea hacer?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
           Pnlmenucito.remove(PnlProveedor1);
           Pnlmenucito.revalidate();
           Pnlmenucito.repaint();
        }
    }//GEN-LAST:event_BtnModificar_Pedido1ActionPerformed

    private void BtnModificar_Pedido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificar_Pedido2ActionPerformed
        String [] opciones={"Eliminar peticion producto","Cancelar"};
       int seleccion= JOptionPane.showOptionDialog(this,"¿Qué desea hacer?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
           Pnlmenucito.remove(PnlProveedor2);
           Pnlmenucito.revalidate();
           Pnlmenucito.repaint();
        }
    }//GEN-LAST:event_BtnModificar_Pedido2ActionPerformed

    private void BtnModificar_Pedido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificar_Pedido3ActionPerformed
        String [] opciones={"Eliminar peticion producto","Cancelar"};
       int seleccion= JOptionPane.showOptionDialog(this,"¿Qué desea hacer?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
           Pnlmenucito.remove(PnlProveedor3);
           Pnlmenucito.revalidate();
           Pnlmenucito.repaint();
        }
    }//GEN-LAST:event_BtnModificar_Pedido3ActionPerformed

    private void BtnModificar_Pedido4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificar_Pedido4ActionPerformed
        String [] opciones={"Eliminar peticion producto","Cancelar"};
       int seleccion= JOptionPane.showOptionDialog(this,"¿Qué desea hacer?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
           Pnlmenucito.remove(PnlProveedor4);
           Pnlmenucito.revalidate();
           Pnlmenucito.repaint();
        }
    }//GEN-LAST:event_BtnModificar_Pedido4ActionPerformed

    private void BtnModificar_Pedido5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificar_Pedido5ActionPerformed
        String [] opciones={"Eliminar peticion producto","Cancelar"};
       int seleccion= JOptionPane.showOptionDialog(this,"¿Qué desea hacer?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
           Pnlmenucito.remove(PnlProveedor5);
           Pnlmenucito.revalidate();
           Pnlmenucito.repaint();
        }
    }//GEN-LAST:event_BtnModificar_Pedido5ActionPerformed

    private void BtnModificar_Pedido6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificar_Pedido6ActionPerformed
        String [] opciones={"Eliminar peticion producto","Cancelar"};
       int seleccion= JOptionPane.showOptionDialog(this,"¿Qué desea hacer?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
           Pnlmenucito.remove(PnlProveedor6);
           Pnlmenucito.revalidate();
           Pnlmenucito.repaint();
        }
    }//GEN-LAST:event_BtnModificar_Pedido6ActionPerformed
 public void cantidad_total_sumar(int incremento) {
     int incremento1;
     incremento1=Integer.parseInt(LblProductos_Total.getText());
     incremento1++;
     String resultado1= Integer.toString(incremento1);
     LblProductos_Total.setText(resultado1);
    }
 public void cantidad_total_restar(int incremento) {
     int incremento1;
     incremento1=Integer.parseInt(LblProductos_Total.getText());
     incremento1--;
     String resultado1= Integer.toString(incremento1);
     LblProductos_Total.setText(resultado1);
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Lista_Pedidos_Proveedores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar1;
    private javax.swing.JButton BotonAgregar2;
    private javax.swing.JButton BotonAgregar3;
    private javax.swing.JButton BotonAgregar4;
    private javax.swing.JButton BotonAgregar5;
    private javax.swing.JButton BotonAgregar6;
    private javax.swing.JButton BotonRestar1;
    private javax.swing.JButton BotonRestar2;
    private javax.swing.JButton BotonRestar3;
    private javax.swing.JButton BotonRestar4;
    private javax.swing.JButton BotonRestar5;
    private javax.swing.JButton BotonRestar6;
    private javax.swing.JButton BtnConfirmarPedido;
    private javax.swing.JButton BtnModificar_Pedido1;
    private javax.swing.JButton BtnModificar_Pedido2;
    private javax.swing.JButton BtnModificar_Pedido3;
    private javax.swing.JButton BtnModificar_Pedido4;
    private javax.swing.JButton BtnModificar_Pedido5;
    private javax.swing.JButton BtnModificar_Pedido6;
    private javax.swing.JLabel IncrementoProductio3;
    private javax.swing.JLabel IncrementoProducto1;
    private javax.swing.JLabel IncrementoProducto2;
    private javax.swing.JLabel IncrementoProducto4;
    private javax.swing.JLabel IncrementoProducto5;
    private javax.swing.JLabel IncrementoProducto6;
    private javax.swing.JLabel JlabelMinilogo;
    private javax.swing.JLabel LbTitulito;
    private javax.swing.JLabel LblCopy;
    private javax.swing.JLabel LblDerechos;
    private javax.swing.JLabel LblFoto1;
    private javax.swing.JLabel LblFoto2;
    private javax.swing.JLabel LblFoto3;
    private javax.swing.JLabel LblFoto4;
    private javax.swing.JLabel LblFoto5;
    private javax.swing.JLabel LblFoto6;
    private javax.swing.JLabel LblFoto_Riesgo1;
    private javax.swing.JLabel LblFoto_Riesgo2;
    private javax.swing.JLabel LblFoto_Riesgo3;
    private javax.swing.JLabel LblFoto_Riesgo4;
    private javax.swing.JLabel LblFoto_Riesgo5;
    private javax.swing.JLabel LblFoto_Riesgo6;
    private javax.swing.JLabel LblMiniLogo;
    private javax.swing.JLabel LblMinifoto;
    private javax.swing.JLabel LblNivel_Riesgo1;
    private javax.swing.JLabel LblNivel_Riesgo2;
    private javax.swing.JLabel LblNivel_Riesgo3;
    private javax.swing.JLabel LblNivel_Riesgo4;
    private javax.swing.JLabel LblNivel_Riesgo5;
    private javax.swing.JLabel LblNivel_Riesgo6;
    private javax.swing.JLabel LblNombreProducto1;
    private javax.swing.JLabel LblNombreProducto2;
    private javax.swing.JLabel LblNombreProducto3;
    private javax.swing.JLabel LblNombreProducto4;
    private javax.swing.JLabel LblNombreProducto5;
    private javax.swing.JLabel LblNombreProducto6;
    private javax.swing.JLabel LblNombreProveedor1;
    private javax.swing.JLabel LblNombreProveedor2;
    private javax.swing.JLabel LblNombreProveedor3;
    private javax.swing.JLabel LblNombreProveedor4;
    private javax.swing.JLabel LblNombreProveedor5;
    private javax.swing.JLabel LblNombreProveedor6;
    private javax.swing.JLabel LblProductos_Total;
    private javax.swing.JLabel LblProveedor1;
    private javax.swing.JLabel LblProveedor2;
    private javax.swing.JLabel LblProveedor3;
    private javax.swing.JLabel LblProveedor4;
    private javax.swing.JLabel LblProveedor5;
    private javax.swing.JLabel LblProveedor6;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo2;
    private javax.swing.JLabel LblTitulo3;
    private javax.swing.JLabel LblTitulo4;
    private javax.swing.JLabel LblTitulo5;
    private javax.swing.JLabel LblTitulo6;
    private javax.swing.JLabel LblTituloStock1;
    private javax.swing.JLabel LblTituloStock2;
    private javax.swing.JLabel LblTituloStock3;
    private javax.swing.JLabel LblTituloStock4;
    private javax.swing.JLabel LblTituloStock5;
    private javax.swing.JLabel LblTituloStock6;
    private javax.swing.JLabel LblTituloSuministrado1;
    private javax.swing.JLabel LblTituloSuministrado2;
    private javax.swing.JLabel LblTituloSuministrado3;
    private javax.swing.JLabel LblTituloSuministrado4;
    private javax.swing.JLabel LblTituloSuministrado5;
    private javax.swing.JLabel LblTituloSuministrado6;
    private javax.swing.JLabel Lblproveedor1;
    private javax.swing.JLabel Lblproveedor2;
    private javax.swing.JLabel Lblproveedor3;
    private javax.swing.JLabel Lblproveedor4;
    private javax.swing.JLabel Lblproveedor5;
    private javax.swing.JLabel Lblproveedor6;
    private javax.swing.JPanel PnlCuadro;
    private javax.swing.JPanel PnlCuadro1;
    private javax.swing.JPanel PnlCuadro10;
    private javax.swing.JPanel PnlCuadro11;
    private javax.swing.JPanel PnlCuadro2;
    private javax.swing.JPanel PnlCuadro3;
    private javax.swing.JPanel PnlCuadro4;
    private javax.swing.JPanel PnlCuadro5;
    private javax.swing.JPanel PnlCuadro6;
    private javax.swing.JPanel PnlCuadro7;
    private javax.swing.JPanel PnlCuadro8;
    private javax.swing.JPanel PnlCuadro9;
    private javax.swing.JPanel PnlEncabezado;
    private javax.swing.JPanel PnlInicio;
    private javax.swing.JScrollPane PnlMenu;
    private javax.swing.JPanel PnlPie;
    private javax.swing.JPanel PnlProveedor1;
    private javax.swing.JPanel PnlProveedor2;
    private javax.swing.JPanel PnlProveedor3;
    private javax.swing.JPanel PnlProveedor4;
    private javax.swing.JPanel PnlProveedor5;
    private javax.swing.JPanel PnlProveedor6;
    private javax.swing.JPanel Pnlmenucito;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables


}
