/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import javax.swing.JFrame;

/**
 *
 * @author MEDAC
 */
public class VentanaGestionProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaGestionProductos.class.getName());

    /**
     * Creates new form VentanaGestionProductos
     */
    public VentanaGestionProductos() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlTotal = new javax.swing.JPanel();
        PnlNorte = new javax.swing.JPanel();
        btnLogo = new javax.swing.JButton();
        PnlAlertas = new javax.swing.JPanel();
        lbbAlertas = new javax.swing.JLabel();
        lblIconoA = new javax.swing.JLabel();
        lblCritico = new javax.swing.JLabel();
        lblIconoC = new javax.swing.JLabel();
        PnlBuscar = new javax.swing.JPanel();
        PnlBarra = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        PnlLupa = new javax.swing.JPanel();
        btnLupa = new javax.swing.JButton();
        PnlPerfil = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();
        lblPerfil = new javax.swing.JLabel();
        PnlOeste = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlTotal.setLayout(new java.awt.BorderLayout());

        PnlNorte.setBackground(new java.awt.Color(153, 153, 153));
        PnlNorte.setLayout(new java.awt.GridBagLayout());

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        PnlNorte.add(btnLogo, gridBagConstraints);

        PnlAlertas.setLayout(new java.awt.GridBagLayout());

        lbbAlertas.setText("jLabel1");
        PnlAlertas.add(lbbAlertas, new java.awt.GridBagConstraints());

        lblIconoA.setText("jLabel1");
        PnlAlertas.add(lblIconoA, new java.awt.GridBagConstraints());

        lblCritico.setText("jLabel1");
        PnlAlertas.add(lblCritico, new java.awt.GridBagConstraints());

        lblIconoC.setText("jLabel1");
        PnlAlertas.add(lblIconoC, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.1;
        PnlNorte.add(PnlAlertas, gridBagConstraints);

        PnlBuscar.setLayout(new java.awt.GridBagLayout());

        PnlBarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBuscar.setText("   Buscar Productos                                        ");

        javax.swing.GroupLayout PnlBarraLayout = new javax.swing.GroupLayout(PnlBarra);
        PnlBarra.setLayout(PnlBarraLayout);
        PnlBarraLayout.setHorizontalGroup(
            PnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlBarraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblBuscar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PnlBarraLayout.setVerticalGroup(
            PnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlBarraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblBuscar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PnlBuscar.add(PnlBarra, gridBagConstraints);

        PnlLupa.setBackground(new java.awt.Color(255, 255, 0));

        btnLupa.setBackground(new java.awt.Color(255, 255, 0));
        btnLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        btnLupa.setOpaque(true);

        javax.swing.GroupLayout PnlLupaLayout = new javax.swing.GroupLayout(PnlLupa);
        PnlLupa.setLayout(PnlLupaLayout);
        PnlLupaLayout.setHorizontalGroup(
            PnlLupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PnlLupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlLupaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnLupa)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PnlLupaLayout.setVerticalGroup(
            PnlLupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PnlLupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnlLupaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnLupa)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PnlBuscar.add(PnlLupa, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        PnlNorte.add(PnlBuscar, gridBagConstraints);

        PnlPerfil.setLayout(new java.awt.GridBagLayout());

        lblUsuario.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlPerfil.add(lblUsuario, gridBagConstraints);

        BtnCerrar.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlPerfil.add(BtnCerrar, gridBagConstraints);

        lblPerfil.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        PnlPerfil.add(lblPerfil, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        PnlNorte.add(PnlPerfil, gridBagConstraints);

        PnlTotal.add(PnlNorte, java.awt.BorderLayout.PAGE_START);

        PnlOeste.setBackground(new java.awt.Color(153, 153, 153));
        PnlOeste.setPreferredSize(new java.awt.Dimension(150, 400));

        javax.swing.GroupLayout PnlOesteLayout = new javax.swing.GroupLayout(PnlOeste);
        PnlOeste.setLayout(PnlOesteLayout);
        PnlOesteLayout.setHorizontalGroup(
            PnlOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        PnlOesteLayout.setVerticalGroup(
            PnlOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        PnlTotal.add(PnlOeste, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaGestionProductos().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JPanel PnlAlertas;
    private javax.swing.JPanel PnlBarra;
    private javax.swing.JPanel PnlBuscar;
    private javax.swing.JPanel PnlLupa;
    private javax.swing.JPanel PnlNorte;
    private javax.swing.JPanel PnlOeste;
    private javax.swing.JPanel PnlPerfil;
    private javax.swing.JPanel PnlTotal;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnLupa;
    private javax.swing.JLabel lbbAlertas;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCritico;
    private javax.swing.JLabel lblIconoA;
    private javax.swing.JLabel lblIconoC;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
