/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

/**
 *
 * @author MEDAC
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlUsuarioPassword = new javax.swing.JPanel();
        lblTituloCostaMarket = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        pfContra = new javax.swing.JPasswordField();
        btnAcceder = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        pnlPrincipal.setAlignmentX(0.5F);
        pnlPrincipal.setAlignmentY(0.5F);
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(1920, 1080));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(1920, 1080));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUsuarioPassword.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuarioPassword.setMaximumSize(new java.awt.Dimension(1920, 1080));
        pnlUsuarioPassword.setMinimumSize(new java.awt.Dimension(1920, 1080));
        pnlUsuarioPassword.setLayout(new java.awt.GridBagLayout());

        lblTituloCostaMarket.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloCostaMarket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCostaMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotocostamarket.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlUsuarioPassword.add(lblTituloCostaMarket, gridBagConstraints);

        txtDNI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDNI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDNI.setText("DNI/NIF o código de empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 125, 5, 125);
        pnlUsuarioPassword.add(txtDNI, gridBagConstraints);

        pfContra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pfContra.setText("Contraseña");
        pfContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfContraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 125, 5, 125);
        pnlUsuarioPassword.add(pfContra, gridBagConstraints);

        btnAcceder.setBackground(new java.awt.Color(255, 102, 102));
        btnAcceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceder.setText("Iniciar Sesión");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 125, 5, 125);
        pnlUsuarioPassword.add(btnAcceder, gridBagConstraints);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido de Nuevo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnlUsuarioPassword.add(lblBienvenida, gridBagConstraints);

        pnlPrincipal.add(pnlUsuarioPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 730, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfContraActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        */
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblTituloCostaMarket;
    private javax.swing.JPasswordField pfContra;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlUsuarioPassword;
    private javax.swing.JTextField txtDNI;
    // End of variables declaration//GEN-END:variables
}
