/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Darío
 */
public class Ventana_Creacion_Producto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_Creacion_Producto.class.getName());
String nombre;
    /**
     * Creates new form Ventana_Creacion_Producto
     */
    public Ventana_Creacion_Producto() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        texto_inicial();
    }
   public Ventana_Creacion_Producto(String nombre) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        texto_inicial();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        test_anti_alcohol = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        PnlEncabezado = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblMinifoto = new javax.swing.JLabel();
        Pnl_Creacionproducto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Btn_Cargar_producto = new javax.swing.JButton();
        LblTitulo_numeroref_producto_creado = new javax.swing.JLabel();
        TxtProducto = new javax.swing.JTextField();
        LblTitulo_restriccion_edad = new javax.swing.JLabel();
        LblTitulo_producto_creado = new javax.swing.JLabel();
        TxtCodigo_Referencia = new javax.swing.JTextField();
        Spinner_Precio_inicial = new javax.swing.JSpinner();
        LblPrecio_Inicial = new javax.swing.JLabel();
        No_Alcohol = new javax.swing.JRadioButton();
        Si_Alcohol = new javax.swing.JRadioButton();
        Pnl_Producto = new javax.swing.JPanel();
        LblFoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        PnlEncabezado.setBackground(new java.awt.Color(102, 102, 102));
        PnlEncabezado.setLayout(new java.awt.GridBagLayout());

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("CREACIÓN PRODUCTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        PnlEncabezado.add(LblTitulo, gridBagConstraints);

        LblMinifoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 9, 0);
        PnlEncabezado.add(LblMinifoto, gridBagConstraints);

        jPanel2.add(PnlEncabezado, java.awt.BorderLayout.PAGE_START);

        Pnl_Creacionproducto.setBackground(new java.awt.Color(204, 153, 255));
        Pnl_Creacionproducto.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(jPanel3, gridBagConstraints);

        Btn_Cargar_producto.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Cargar_producto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Btn_Cargar_producto.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Cargar_producto.setText("Cargar Fotografia");
        Btn_Cargar_producto.setToolTipText("");
        Btn_Cargar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cargar_productoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(Btn_Cargar_producto, gridBagConstraints);

        LblTitulo_numeroref_producto_creado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LblTitulo_numeroref_producto_creado.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo_numeroref_producto_creado.setText("Codigo_Referencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(LblTitulo_numeroref_producto_creado, gridBagConstraints);

        TxtProducto.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(TxtProducto, gridBagConstraints);

        LblTitulo_restriccion_edad.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LblTitulo_restriccion_edad.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo_restriccion_edad.setText("Restrición de edad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 9);
        jPanel1.add(LblTitulo_restriccion_edad, gridBagConstraints);

        LblTitulo_producto_creado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LblTitulo_producto_creado.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo_producto_creado.setText("Nombre_Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(LblTitulo_producto_creado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(TxtCodigo_Referencia, gridBagConstraints);

        Spinner_Precio_inicial.setMinimumSize(new java.awt.Dimension(108, 26));
        Spinner_Precio_inicial.setPreferredSize(new java.awt.Dimension(168, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(Spinner_Precio_inicial, gridBagConstraints);

        LblPrecio_Inicial.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LblPrecio_Inicial.setForeground(new java.awt.Color(0, 0, 0));
        LblPrecio_Inicial.setText("Precio_inicial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(LblPrecio_Inicial, gridBagConstraints);

        test_anti_alcohol.add(No_Alcohol);
        No_Alcohol.setForeground(new java.awt.Color(0, 0, 0));
        No_Alcohol.setText("Producto normal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 9);
        jPanel1.add(No_Alcohol, gridBagConstraints);

        test_anti_alcohol.add(Si_Alcohol);
        Si_Alcohol.setForeground(new java.awt.Color(0, 0, 0));
        Si_Alcohol.setText("Producto +18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 9);
        jPanel1.add(Si_Alcohol, gridBagConstraints);

        javax.swing.GroupLayout Pnl_ProductoLayout = new javax.swing.GroupLayout(Pnl_Producto);
        Pnl_Producto.setLayout(Pnl_ProductoLayout);
        Pnl_ProductoLayout.setHorizontalGroup(
            Pnl_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Pnl_ProductoLayout.setVerticalGroup(
            Pnl_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(Pnl_Producto, gridBagConstraints);

        LblFoto.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(LblFoto, gridBagConstraints);

        Pnl_Creacionproducto.add(jPanel1, new java.awt.GridBagConstraints());

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CREAR");
        jButton1.setPreferredSize(new java.awt.Dimension(265, 59));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Pnl_Creacionproducto.add(jButton1, gridBagConstraints);

        jPanel2.add(Pnl_Creacionproducto, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Cargar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cargar_productoActionPerformed
          JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes (JPG o PNG)", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            try {
                Pnl_Producto.setVisible(false);
                File archivo = fileChooser.getSelectedFile();
                BufferedImage imagen = ImageIO.read(archivo);

                if (imagen != null) {
                    Image imagenEscalada = imagen.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                    LblFoto.setIcon(new ImageIcon(imagenEscalada));
                    LblFoto.setText("");
                } else {
                    // Archivo leído ok, pero no es una imagen válida, puede estar corrupto
                    JOptionPane.showMessageDialog(
                            this,
                            "El archivo seleccionado no es una imagen válida",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            } catch (IOException ex) {
                // No se ha podido leer el archivo: problema de acceso, no existe, sin permisos...
                JOptionPane.showMessageDialog(
                        this,
                        "Se ha producido un error al cargar la imagen: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_Btn_Cargar_productoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numero_referencia=TxtCodigo_Referencia.getText();
       String nombre_producto=TxtProducto.getText();
       int cambio_precio = (int) Spinner_Precio_inicial.getValue(); //Lo usamos para trasnformar el valor del JSpinner en un int 
       Boolean alcohol;
        if(cambio_precio<=0){
       JOptionPane.showMessageDialog(this, "Error", "No se puede poner precio negativos, a menos que quieras perder dinero", JOptionPane.INFORMATION_MESSAGE);
       }else{
        JOptionPane.showMessageDialog(this, "Objeto creado", "CREACION COMPLETADA", JOptionPane.INFORMATION_MESSAGE);
      
       
       if(Si_Alcohol.isSelected()==true){
           alcohol=true;
       }else{
           alcohol=false;
       }
       VentanaPrincipalAdministrador vuelta_pagAdmin=new VentanaPrincipalAdministrador(numero_referencia,nombre_producto,cambio_precio,alcohol);
       vuelta_pagAdmin.setVisible(true);
       this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Ventana_Creacion_Producto().setVisible(true));
    }
    private void texto_inicial(){
    // Texto inicial y color
    TxtProducto.setText("Escribe aqui el nombre del producto");
    TxtProducto.setForeground(Color.GRAY);

    TxtCodigo_Referencia.setText("Escribe aqui el numero de referencia");
    TxtCodigo_Referencia.setForeground(Color.GRAY);

    // Listener para TxtProducto
    TxtProducto.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (TxtProducto.getText().equals("Escribe aqui el nombre del producto")) {
                TxtProducto.setText("");
                TxtProducto.setForeground(Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (TxtProducto.getText().trim().isEmpty()) {
                TxtProducto.setText("Escribe aqui el nombre del producto");
                TxtProducto.setForeground(Color.GRAY);
            }
        }
    });

    // Listener para TxtCodigo_Referencia
    TxtCodigo_Referencia.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (TxtCodigo_Referencia.getText().equals("Escribe aqui el numero de referencia")) {
                TxtCodigo_Referencia.setText("");
                TxtCodigo_Referencia.setForeground(Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (TxtCodigo_Referencia.getText().trim().isEmpty()) {
                TxtCodigo_Referencia.setText("Escribe aqui el numero de referencia");
                TxtCodigo_Referencia.setForeground(Color.GRAY);
            }
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cargar_producto;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JLabel LblMinifoto;
    private javax.swing.JLabel LblPrecio_Inicial;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo_numeroref_producto_creado;
    private javax.swing.JLabel LblTitulo_producto_creado;
    private javax.swing.JLabel LblTitulo_restriccion_edad;
    private javax.swing.JRadioButton No_Alcohol;
    private javax.swing.JPanel PnlEncabezado;
    private javax.swing.JPanel Pnl_Creacionproducto;
    private javax.swing.JPanel Pnl_Producto;
    private javax.swing.JRadioButton Si_Alcohol;
    private javax.swing.JSpinner Spinner_Precio_inicial;
    private javax.swing.JTextField TxtCodigo_Referencia;
    private javax.swing.JTextField TxtProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.ButtonGroup test_anti_alcohol;
    // End of variables declaration//GEN-END:variables
}
