/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

/**
 *
 * @author Coron
 */
public class VentanaGestiónEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestiónEmpleado
     */
    public VentanaGestiónEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlCabezera = new javax.swing.JPanel();
        lblLogoCostaMarket = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        pnlPerfil = new javax.swing.JPanel();
        lblFotoEmpleado = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblIDEmpleadoCabeza = new javax.swing.JLabel();
        pnlPiePagina = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        pnlCreacion = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblNombreApellido = new javax.swing.JLabel();
        txtNombreApellido = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        txtNumeroDNI = new javax.swing.JTextField();
        lblIDEmpleado = new javax.swing.JLabel();
        txtIDEmpleado = new javax.swing.JTextField();
        btnCambiarPasswd = new javax.swing.JButton();
        btnCrearPerfil = new javax.swing.JButton();
        btnSalirSinGuardar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Empleado");
        setPreferredSize(new java.awt.Dimension(680, 494));

        pnlPrincipal.setMinimumSize(new java.awt.Dimension(680, 172));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(664, 234));
        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlCabezera.setBackground(new java.awt.Color(102, 102, 102));
        pnlCabezera.setPreferredSize(new java.awt.Dimension(473, 70));
        pnlCabezera.setLayout(new java.awt.GridBagLayout());

        lblLogoCostaMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        pnlCabezera.add(lblLogoCostaMarket, gridBagConstraints);

        txtBuscador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBuscador.setText("Introduzca ID o código de Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        pnlCabezera.add(txtBuscador, gridBagConstraints);

        pnlPerfil.setLayout(new java.awt.GridBagLayout());

        lblFotoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        pnlPerfil.add(lblFotoEmpleado, gridBagConstraints);

        btnCerrarSesion.setForeground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlPerfil.add(btnCerrarSesion, gridBagConstraints);

        lblIDEmpleadoCabeza.setText("ID EMPLEADO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlPerfil.add(lblIDEmpleadoCabeza, gridBagConstraints);

        pnlCabezera.add(pnlPerfil, new java.awt.GridBagConstraints());

        pnlPrincipal.add(pnlCabezera, java.awt.BorderLayout.PAGE_START);

        pnlPiePagina.setBackground(new java.awt.Color(102, 102, 102));
        pnlPiePagina.setPreferredSize(new java.awt.Dimension(473, 70));
        pnlPiePagina.setLayout(new java.awt.GridBagLayout());

        btnSalir.setBackground(new java.awt.Color(255, 153, 153));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 289, 25, 306);
        pnlPiePagina.add(btnSalir, gridBagConstraints);

        pnlPrincipal.add(pnlPiePagina, java.awt.BorderLayout.PAGE_END);

        pnlCreacion.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreacion.setLayout(new java.awt.GridBagLayout());

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlCreacion.add(lblFoto, gridBagConstraints);

        lblNombreApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreApellido.setText("Nombre y Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlCreacion.add(lblNombreApellido, gridBagConstraints);

        txtNombreApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreApellido.setText("Nombre y Apellidos del empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlCreacion.add(txtNombreApellido, gridBagConstraints);

        lblDNI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(0, 0, 0));
        lblDNI.setText("DNI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlCreacion.add(lblDNI, gridBagConstraints);

        txtNumeroDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroDNI.setText("Número del DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlCreacion.add(txtNumeroDNI, gridBagConstraints);

        lblIDEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblIDEmpleado.setText("ID de Empleado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnlCreacion.add(lblIDEmpleado, gridBagConstraints);

        txtIDEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDEmpleado.setText("ID del Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlCreacion.add(txtIDEmpleado, gridBagConstraints);

        btnCambiarPasswd.setBackground(new java.awt.Color(255, 255, 255));
        btnCambiarPasswd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCambiarPasswd.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarPasswd.setText("Cambiar Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlCreacion.add(btnCambiarPasswd, gridBagConstraints);

        btnCrearPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearPerfil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCrearPerfil.setForeground(new java.awt.Color(0, 153, 204));
        btnCrearPerfil.setText("Crear Nuevo Perfil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        pnlCreacion.add(btnCrearPerfil, gridBagConstraints);

        btnSalirSinGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirSinGuardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSalirSinGuardar.setForeground(new java.awt.Color(255, 51, 51));
        btnSalirSinGuardar.setText("Salir sin guardar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        pnlCreacion.add(btnSalirSinGuardar, gridBagConstraints);

        btnGuardarCambios.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarCambios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGuardarCambios.setForeground(new java.awt.Color(102, 255, 102));
        btnGuardarCambios.setText("Guardar Cambios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        pnlCreacion.add(btnGuardarCambios, gridBagConstraints);

        pnlPrincipal.add(pnlCreacion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestiónEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarPasswd;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearPerfil;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalirSinGuardar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFotoEmpleado;
    private javax.swing.JLabel lblIDEmpleado;
    private javax.swing.JLabel lblIDEmpleadoCabeza;
    private javax.swing.JLabel lblLogoCostaMarket;
    private javax.swing.JLabel lblNombreApellido;
    private javax.swing.JPanel pnlCabezera;
    private javax.swing.JPanel pnlCreacion;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JPanel pnlPiePagina;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtIDEmpleado;
    private javax.swing.JTextField txtNombreApellido;
    private javax.swing.JTextField txtNumeroDNI;
    // End of variables declaration//GEN-END:variables
}
