/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import javax.swing.ImageIcon;

/**
 *
 * @author MEDAC
 */
public class VentanaPrincipalEmpleado extends javax.swing.JFrame {
    String nombre;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipalEmpleado.class.getName());

    /**
     * Creates new form VentanaPrincipalEmpleado
     */
    private String nombreUsuario;
    private String dniUsuario;
    public VentanaPrincipalEmpleado() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
            jLabel3.setText(" ");
         jLabel3.setIcon(new ImageIcon(getClass().getResource("/bicho_lidel.png")));
                 jTextField1.setText(nombre);
    }
     public VentanaPrincipalEmpleado(String nombre) {
        initComponents();
        this.nombre=nombre;
        setExtendedState(MAXIMIZED_BOTH);
        jTextField1.setText(nombre);
        jLabel3.setText(" ");
                jLabel3.setIcon(new ImageIcon(getClass().getResource("/bicho_lidel.png")));
    }
        public VentanaPrincipalEmpleado(String nombre, String dni) {
       initComponents();
       this.nombreUsuario = nombre;
       this.dniUsuario = dni;
          jTextField1.setText(nombre);
        jLabel3.setText(" ");
                jLabel3.setIcon(new ImageIcon(getClass().getResource("/lobatito.jpg")));
                        setExtendedState(MAXIMIZED_BOTH);

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlMensaje = new javax.swing.JPanel();
        lblFotoLogo = new javax.swing.JLabel();
        lblTextoBienvenida = new javax.swing.JLabel();
        pnlSeccionEmpleado = new javax.swing.JPanel();
        BtnCerrar_sesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pnlCopy = new javax.swing.JPanel();
        lblFotoLogo2 = new javax.swing.JLabel();
        txtCopy = new javax.swing.JLabel();
        lblLogoCopy = new javax.swing.JLabel();
        pnlBoton = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVentaYCaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Principal del Empleado");
        setResizable(false);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlMensaje.setBackground(new java.awt.Color(255, 204, 51));
        pnlMensaje.setForeground(new java.awt.Color(255, 255, 255));
        pnlMensaje.setLayout(new java.awt.GridBagLayout());

        lblFotoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        lblFotoLogo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        pnlMensaje.add(lblFotoLogo, gridBagConstraints);

        lblTextoBienvenida.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        lblTextoBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoBienvenida.setText("Un gusto verle de nuevo!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        pnlMensaje.add(lblTextoBienvenida, gridBagConstraints);

        pnlSeccionEmpleado.setLayout(new java.awt.GridBagLayout());

        BtnCerrar_sesion.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar_sesion.setForeground(new java.awt.Color(255, 0, 0));
        BtnCerrar_sesion.setText("Cerrar Sesión");
        BtnCerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrar_sesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlSeccionEmpleado.add(BtnCerrar_sesion, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        pnlSeccionEmpleado.add(jLabel3, gridBagConstraints);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("ID empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlSeccionEmpleado.add(jTextField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        pnlMensaje.add(pnlSeccionEmpleado, gridBagConstraints);

        pnlPrincipal.add(pnlMensaje, java.awt.BorderLayout.PAGE_START);

        pnlCopy.setBackground(new java.awt.Color(255, 204, 51));
        pnlCopy.setPreferredSize(new java.awt.Dimension(555, 70));
        pnlCopy.setLayout(new java.awt.GridBagLayout());

        lblFotoLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        pnlCopy.add(lblFotoLogo2, new java.awt.GridBagConstraints());

        txtCopy.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txtCopy.setForeground(new java.awt.Color(0, 0, 0));
        txtCopy.setText("Todos los derechos reservados");
        pnlCopy.add(txtCopy, new java.awt.GridBagConstraints());

        lblLogoCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copyright.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        pnlCopy.add(lblLogoCopy, gridBagConstraints);

        pnlPrincipal.add(pnlCopy, java.awt.BorderLayout.PAGE_END);

        pnlBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        pnlBoton.setMinimumSize(new java.awt.Dimension(680, 46));
        pnlBoton.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        btnProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProductos.setText("Gestión de Productos, Inventario y Stock");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        pnlBoton.add(btnProductos);

        btnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPedidos.setText("Gestión de Pedidos a Proveedores");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        pnlBoton.add(btnPedidos);

        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.setText("Modificar Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        pnlBoton.add(btnClientes);

        btnVentaYCaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVentaYCaja.setText("Ventas y Cajas");
        btnVentaYCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaYCajaActionPerformed(evt);
            }
        });
        pnlBoton.add(btnVentaYCaja);

        pnlPrincipal.add(pnlBoton, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        
        VentanaGestionProductos ventanaGProductos= new VentanaGestionProductos(nombre);
        ventanaGProductos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
        Lista_Pedidos_Proveedores ListaPedidoProv= new Lista_Pedidos_Proveedores(nombre);
        ListaPedidoProv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        VentanaModificarClientes ventanaCliente = new VentanaModificarClientes(nombre);
        ventanaCliente.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVentaYCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaYCajaActionPerformed
        // TODO add your handling code here:
        VentanaVentas ir_ventas_empleado=new VentanaVentas(nombre);
        ir_ventas_empleado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentaYCajaActionPerformed

    private void BtnCerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrar_sesionActionPerformed
        // TODO add your handling code here:
        VentanaLogin VenLo= new VentanaLogin();
        VenLo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCerrar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipalEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar_sesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnVentaYCaja;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFotoLogo;
    private javax.swing.JLabel lblFotoLogo2;
    private javax.swing.JLabel lblLogoCopy;
    private javax.swing.JLabel lblTextoBienvenida;
    private javax.swing.JPanel pnlBoton;
    private javax.swing.JPanel pnlCopy;
    private javax.swing.JPanel pnlMensaje;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSeccionEmpleado;
    private javax.swing.JLabel txtCopy;
    // End of variables declaration//GEN-END:variables
}
