/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import javax.swing.ImageIcon;

/**
 *
 * @author MEDAC
 */
public class VentanaPrincipalAdministrador extends javax.swing.JFrame {
    String numero_referencia;
            String nombre_producto;
                    int precio;
                    boolean alcohol;
            String nombre;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipalAdministrador.class.getName());

    /**
     * Creates new form VentanaPrincipalAdministrador
     */
    public VentanaPrincipalAdministrador() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
        public VentanaPrincipalAdministrador(String numero_referencia,String nombre_producto, int precio,boolean alcohol) {
                    initComponents();
        this.numero_referencia=numero_referencia;
        this.nombre_producto=nombre_producto;
        this.precio=precio;
        this.alcohol=alcohol;
        lblTextoBienvenida.setText("Esto es una prueba de dario, el producto transferido es:"+this.nombre_producto+" el numero de ref es:"+this.numero_referencia+"'el precio y si tiene alcohol es:"+precio+alcohol);
        //NESTOR ESTO LO HA HECHO DARIO QUE ES PARA LA CONEXION DE PAGINAS ENTRE LA PRINCIPAL DEL ADMIN Y YA LA CREACION DEL PRODUCTO, HAY QUE UNIRLA AL CATALOGO Y HACER QUE SE AGREGE ESTE PRODUCTO
        //Esta conectado al label que tenias en el encabezado el JLABEL1 
    }
          public VentanaPrincipalAdministrador(String nombre) {
        initComponents();
        this.nombre=nombre;
        jTextField1.setText(nombre);
          jLabel3.setText(" ");
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/lobatito.jpg")));
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlCopy = new javax.swing.JPanel();
        pnlBotonesAdmin = new javax.swing.JPanel();
        pnlMensaje = new javax.swing.JPanel();
        lblFotoLogo = new javax.swing.JLabel();
        lblTextoBienvenida = new javax.swing.JLabel();
        pnlSeccionEmpleado = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Principal Administrador");
        setPreferredSize(new java.awt.Dimension(680, 468));

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlCopy.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnlCopyLayout = new javax.swing.GroupLayout(pnlCopy);
        pnlCopy.setLayout(pnlCopyLayout);
        pnlCopyLayout.setHorizontalGroup(
            pnlCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        pnlCopyLayout.setVerticalGroup(
            pnlCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlCopy, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnlBotonesAdminLayout = new javax.swing.GroupLayout(pnlBotonesAdmin);
        pnlBotonesAdmin.setLayout(pnlBotonesAdminLayout);
        pnlBotonesAdminLayout.setHorizontalGroup(
            pnlBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        pnlBotonesAdminLayout.setVerticalGroup(
            pnlBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlBotonesAdmin, java.awt.BorderLayout.CENTER);

        pnlMensaje.setBackground(new java.awt.Color(255, 204, 51));
        pnlMensaje.setForeground(new java.awt.Color(255, 255, 255));
        pnlMensaje.setLayout(new java.awt.GridBagLayout());

        lblFotoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        lblFotoLogo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        pnlMensaje.add(lblFotoLogo, gridBagConstraints);

        lblTextoBienvenida.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        lblTextoBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoBienvenida.setText("Un gusto verle de nuevo!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        pnlMensaje.add(lblTextoBienvenida, gridBagConstraints);

        pnlSeccionEmpleado.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cerrar Sesión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlSeccionEmpleado.add(jButton1, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        pnlSeccionEmpleado.add(jLabel3, gridBagConstraints);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("ID empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlSeccionEmpleado.add(jTextField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        pnlMensaje.add(pnlSeccionEmpleado, gridBagConstraints);

        pnlPrincipal.add(pnlMensaje, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipalAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFotoLogo;
    private javax.swing.JLabel lblTextoBienvenida;
    private javax.swing.JPanel pnlBotonesAdmin;
    private javax.swing.JPanel pnlCopy;
    private javax.swing.JPanel pnlMensaje;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSeccionEmpleado;
    // End of variables declaration//GEN-END:variables
}
