/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class VentanaPrincipalAdministrador extends javax.swing.JFrame {
    String numero_referencia;
            String nombre_producto;
                    int precio;
                    boolean alcohol;
            String nombre;
            String foto;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipalAdministrador.class.getName());

    /**
     * Creates new form VentanaPrincipalAdministrador
     */
    public VentanaPrincipalAdministrador() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
    }
        public VentanaPrincipalAdministrador(String numero_referencia,String nombre_producto, int precio,boolean alcohol) {
                    initComponents();
        this.numero_referencia=numero_referencia;
        this.nombre_producto=nombre_producto;
        this.precio=precio;
        this.alcohol=alcohol;
        jLabel1.setText("el producto creado es:"+this.nombre_producto+" con  numero de referencia:"+this.numero_referencia+" con un precio de "+this.precio+" y lleva alcohol? o es +18:"+alcohol);
    }
          public VentanaPrincipalAdministrador(String nombre) {
        initComponents();
        this.nombre=nombre;
        txtIDEmpleado.setText(nombre);
        lblFotoPerfil.setIcon(new ImageIcon(getClass().getResource("/lobatito.jpg")));
        setExtendedState(MAXIMIZED_BOTH);
        foto=lblFotoPerfil.toString();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlCabezera = new javax.swing.JPanel();
        lblLogoCostaMarket = new javax.swing.JLabel();
        txtMensajeAdmin = new javax.swing.JLabel();
        pnlSeccionCliente = new javax.swing.JPanel();
        lblFotoPerfil = new javax.swing.JLabel();
        txtIDEmpleado = new javax.swing.JTextField();
        btnCerrarSesion = new javax.swing.JButton();
        pnlCopy = new javax.swing.JPanel();
        pnlBotonesAdmin = new javax.swing.JPanel();
        btnGestionEmpleados = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnGestionarPromociones = new javax.swing.JButton();
        btnFuncionesEmpleado = new javax.swing.JButton();
        btnGestionarProveedores = new javax.swing.JButton();
        btnHistoricoVentas = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Principal Administrador");
        setPreferredSize(new java.awt.Dimension(680, 468));

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlCabezera.setBackground(new java.awt.Color(255, 204, 51));
        pnlCabezera.setPreferredSize(new java.awt.Dimension(555, 70));
        pnlCabezera.setLayout(new java.awt.GridBagLayout());

        lblLogoCostaMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minicostamarket.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        pnlCabezera.add(lblLogoCostaMarket, gridBagConstraints);

        txtMensajeAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMensajeAdmin.setForeground(new java.awt.Color(0, 0, 0));
        txtMensajeAdmin.setText("Seleccione un tipo de gestión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        pnlCabezera.add(txtMensajeAdmin, gridBagConstraints);

        pnlSeccionCliente.setBackground(new java.awt.Color(51, 51, 51));
        pnlSeccionCliente.setLayout(new java.awt.GridBagLayout());

        lblFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlSeccionCliente.add(lblFotoPerfil, gridBagConstraints);

        txtIDEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtIDEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtIDEmpleado.setText("ID Admin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlSeccionCliente.add(txtIDEmpleado, gridBagConstraints);

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 51, 51));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlSeccionCliente.add(btnCerrarSesion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        pnlCabezera.add(pnlSeccionCliente, gridBagConstraints);

        pnlPrincipal.add(pnlCabezera, java.awt.BorderLayout.PAGE_START);

        pnlCopy.setBackground(new java.awt.Color(255, 204, 0));
        pnlCopy.setPreferredSize(new java.awt.Dimension(555, 70));

        javax.swing.GroupLayout pnlCopyLayout = new javax.swing.GroupLayout(pnlCopy);
        pnlCopy.setLayout(pnlCopyLayout);
        pnlCopyLayout.setHorizontalGroup(
            pnlCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        pnlCopyLayout.setVerticalGroup(
            pnlCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlCopy, java.awt.BorderLayout.PAGE_END);

        pnlBotonesAdmin.setLayout(new java.awt.GridBagLayout());

        btnGestionEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionEmpleados.setText("Gestionar Empleados");
        btnGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEmpleadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBotonesAdmin.add(btnGestionEmpleados, gridBagConstraints);

        btnModificarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificarProducto.setText("Modificación Producto");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBotonesAdmin.add(btnModificarProducto, gridBagConstraints);

        btnGestionarPromociones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionarPromociones.setText("Gestionar Promociones");
        btnGestionarPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPromocionesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBotonesAdmin.add(btnGestionarPromociones, gridBagConstraints);

        btnFuncionesEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFuncionesEmpleado.setText("Funciones de Empleado");
        btnFuncionesEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionesEmpleadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBotonesAdmin.add(btnFuncionesEmpleado, gridBagConstraints);

        btnGestionarProveedores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionarProveedores.setText("Gestionar Proveedores");
        btnGestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProveedoresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBotonesAdmin.add(btnGestionarProveedores, gridBagConstraints);

        btnHistoricoVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistoricoVentas.setText("Histórico de Ventas");
        btnHistoricoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoVentasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBotonesAdmin.add(btnHistoricoVentas, gridBagConstraints);

        btnInformes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInformes.setText("Informes");
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBotonesAdmin.add(btnInformes, gridBagConstraints);

        jLabel1.setText("Comprobacion_texto producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnlBotonesAdmin.add(jLabel1, gridBagConstraints);

        pnlPrincipal.add(pnlBotonesAdmin, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEmpleadosActionPerformed
         Ventana_Creacion_Producto VenCrePro= new Ventana_Creacion_Producto();
         VenCrePro.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnGestionarEmpleadosActionPerformed

    private void btnPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionesActionPerformed
        // TODO add your handling code here:
        Gestion_Promociones gesPromo= new Gestion_Promociones(nombre);
        gesPromo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPromocionesActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        Lista_Pedidos_Proveedores LisGesPro= new Lista_Pedidos_Proveedores(nombre);
        LisGesPro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnFuncionesEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionesEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaPrincipalEmpleado VenPrinEm= new VentanaPrincipalEmpleado(nombre,foto);
        VenPrinEm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFuncionesEmpleadoActionPerformed

    private void btnGestionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductoActionPerformed
        // TODO add your handling code here:
        VentanaGestionProductos VenGesPro= new VentanaGestionProductos(nombre);
        VenGesPro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionProductoActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        Gestion_ventas_cajasDiarias GesVenCaja= new Gestion_ventas_cajasDiarias(nombre);
        GesVenCaja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Ventana en construcción, por favor seleccione otra opción.","Apartado en construcción.",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnInformesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        VentanaLogin VenLog = new VentanaLogin();
        VenLog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosActionPerformed
        // TODO add your handling code here:
        VentanaGestiónEmpleado VenGesEm= new VentanaGestiónEmpleado(nombre);
        VenGesEm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionEmpleadosActionPerformed

    private void btnGestionarPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPromocionesActionPerformed
        // TODO add your handling code here:
        Gestion_Promociones gestpro= new Gestion_Promociones(nombre);
        gestpro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionarPromocionesActionPerformed

    private void btnGestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProveedoresActionPerformed
        // TODO add your handling code here:
        Lista_Pedidos_Proveedores lispedpro= new Lista_Pedidos_Proveedores(nombre);
        lispedpro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionarProveedoresActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        // TODO add your handling code here:
        VentanaModificacionProductos modifProd= new VentanaModificacionProductos(nombre);
        modifProd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnHistoricoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoVentasActionPerformed
        // TODO add your handling code here:
        Gestion_ventas_cajasDiarias gestvendia= new Gestion_ventas_cajasDiarias(nombre);
        gestvendia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoricoVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipalAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnFuncionesEmpleado;
    private javax.swing.JButton btnGestionEmpleados;
    private javax.swing.JButton btnGestionarPromociones;
    private javax.swing.JButton btnGestionarProveedores;
    private javax.swing.JButton btnHistoricoVentas;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblLogoCostaMarket;
    private javax.swing.JPanel pnlBotonesAdmin;
    private javax.swing.JPanel pnlCabezera;
    private javax.swing.JPanel pnlCopy;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSeccionCliente;
    private javax.swing.JTextField txtIDEmpleado;
    private javax.swing.JLabel txtMensajeAdmin;
    // End of variables declaration//GEN-END:variables
}
