/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosupermecado.componentes;

import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class Pedido_Proveedor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pedido_Proveedor.class.getName());

    /**
     * Creates new form Pedido_Proveedor
     */
    public Pedido_Proveedor() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlProveedor1 = new javax.swing.JPanel();
        LblFoto1 = new javax.swing.JLabel();
        LblNombreProducto1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PnlCuadro = new javax.swing.JPanel();
        LblTitulo1 = new javax.swing.JLabel();
        LblProveedor1 = new javax.swing.JLabel();
        LblTituloStock1 = new javax.swing.JLabel();
        LblNivel_Riesgo1 = new javax.swing.JLabel();
        LblFoto_Riesgo1 = new javax.swing.JLabel();
        BtnModificar_Pedido1 = new javax.swing.JButton();
        IncrementoProducto1 = new javax.swing.JLabel();
        BotonAgregar1 = new javax.swing.JButton();
        BotonRestar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PnlCuadro1 = new javax.swing.JPanel();
        LblTituloSuministrado1 = new javax.swing.JLabel();
        LblNombreProveedor1 = new javax.swing.JLabel();
        Lblproveedor1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlProveedor1.setBackground(new java.awt.Color(204, 153, 255));
        PnlProveedor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        PnlProveedor1.setPreferredSize(new java.awt.Dimension(2600, 404));
        PnlProveedor1.setLayout(new java.awt.GridBagLayout());

        LblFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asturiana.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(LblFoto1, gridBagConstraints);

        LblNombreProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNombreProducto1.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProducto1.setText("Leche Asturiana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(LblNombreProducto1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("20,99 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(jLabel3, gridBagConstraints);

        PnlCuadro.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        PnlCuadro.setMinimumSize(new java.awt.Dimension(500, 100));
        PnlCuadro.setLayout(new java.awt.GridBagLayout());

        LblTitulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo1.setText("Peticion enviada por:");
        PnlCuadro.add(LblTitulo1, new java.awt.GridBagConstraints());

        LblProveedor1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblProveedor1.setForeground(new java.awt.Color(0, 0, 0));
        LblProveedor1.setText("Nombre_Proveedor");
        PnlCuadro.add(LblProveedor1, new java.awt.GridBagConstraints());

        LblTituloStock1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloStock1.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloStock1.setText("Estado de stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro.add(LblTituloStock1, gridBagConstraints);

        LblNivel_Riesgo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblNivel_Riesgo1.setForeground(new java.awt.Color(0, 0, 0));
        LblNivel_Riesgo1.setText("Nivel_Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCuadro.add(LblNivel_Riesgo1, gridBagConstraints);

        LblFoto_Riesgo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFoto_Riesgo1.setForeground(new java.awt.Color(0, 0, 0));
        LblFoto_Riesgo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/riesgobajo.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro.add(LblFoto_Riesgo1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(PnlCuadro, gridBagConstraints);

        BtnModificar_Pedido1.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar_Pedido1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnModificar_Pedido1.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar_Pedido1.setText("MODIFICAR PEDIDO");
        BtnModificar_Pedido1.setPreferredSize(new java.awt.Dimension(300, 27));
        BtnModificar_Pedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificar_Pedido1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(BtnModificar_Pedido1, gridBagConstraints);

        IncrementoProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncrementoProducto1.setForeground(new java.awt.Color(0, 0, 0));
        IncrementoProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoproducto.png"))); // NOI18N
        IncrementoProducto1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(IncrementoProducto1, gridBagConstraints);

        BotonAgregar1.setBackground(new java.awt.Color(0, 255, 0));
        BotonAgregar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonAgregar1.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregar1.setText("+");
        BotonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(BotonAgregar1, gridBagConstraints);

        BotonRestar1.setBackground(new java.awt.Color(255, 0, 51));
        BotonRestar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonRestar1.setForeground(new java.awt.Color(0, 0, 0));
        BotonRestar1.setText("-");
        BotonRestar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(BotonRestar1, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(jLabel5, gridBagConstraints);

        PnlCuadro1.setBackground(new java.awt.Color(255, 255, 255));
        PnlCuadro1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        PnlCuadro1.setMinimumSize(new java.awt.Dimension(400, 100));
        PnlCuadro1.setLayout(new java.awt.GridBagLayout());

        LblTituloSuministrado1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblTituloSuministrado1.setForeground(new java.awt.Color(0, 0, 0));
        LblTituloSuministrado1.setText("Suministrado por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PnlCuadro1.add(LblTituloSuministrado1, gridBagConstraints);

        LblNombreProveedor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNombreProveedor1.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreProveedor1.setText("Nombre_Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        PnlCuadro1.add(LblNombreProveedor1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 38);
        PnlProveedor1.add(PnlCuadro1, gridBagConstraints);

        Lblproveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hacendado.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 15, 50);
        PnlProveedor1.add(Lblproveedor1, gridBagConstraints);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PnlProveedor1.add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PnlProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PnlProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificar_Pedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificar_Pedido1ActionPerformed
        String [] opciones={"Eliminar peticion producto","Cancelar"};
        int seleccion= JOptionPane.showOptionDialog(this,"¿Qué desea hacer?","Modificación de producto",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[1]);
        if(seleccion==0){
            PnlProveedor1.remove(this);
            PnlProveedor1.revalidate();
            PnlProveedor1.repaint();
        }
    }//GEN-LAST:event_BtnModificar_Pedido1ActionPerformed

    private void BotonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar1ActionPerformed
        int incremento1;
        incremento1=Integer.parseInt(IncrementoProducto1.getText());
        incremento1++;
        //cantidad_total_sumar(incremento1); HAY QUE ARREGLAR
        String resultado1= Integer.toString(incremento1);
        IncrementoProducto1.setText(resultado1);

    }//GEN-LAST:event_BotonAgregar1ActionPerformed

    private void BotonRestar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestar1ActionPerformed
        if(IncrementoProducto1.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "No se puede pedir unidades negativas, lo siento", "Imposiblidad", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int incremento1;
            incremento1=Integer.parseInt(IncrementoProducto1.getText());
            incremento1--;
            //cantidad_total_restar(incremento1); HAY QUE ARREGLAR 
            String resultado1= Integer.toString(incremento1);
            IncrementoProducto1.setText(resultado1);
        }

    }//GEN-LAST:event_BotonRestar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pedido_Proveedor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar1;
    private javax.swing.JButton BotonRestar1;
    private javax.swing.JButton BtnModificar_Pedido1;
    private javax.swing.JLabel IncrementoProducto1;
    private javax.swing.JLabel LblFoto1;
    private javax.swing.JLabel LblFoto_Riesgo1;
    private javax.swing.JLabel LblNivel_Riesgo1;
    private javax.swing.JLabel LblNombreProducto1;
    private javax.swing.JLabel LblNombreProveedor1;
    private javax.swing.JLabel LblProveedor1;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTituloStock1;
    private javax.swing.JLabel LblTituloSuministrado1;
    private javax.swing.JLabel Lblproveedor1;
    private javax.swing.JPanel PnlCuadro;
    private javax.swing.JPanel PnlCuadro1;
    private javax.swing.JPanel PnlProveedor1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
