/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectosupermecado.componentes;

import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author MEDAC
 */
public class ProductoGestionProducto extends javax.swing.JPanel {

    /**
     * Creates new form ProductoGestionProducto
     */
    public ProductoGestionProducto() {
        initComponents();
    }

    public ProductoGestionProducto(JButton btnAstock, JButton btnCprecio, JButton btnEproducto, JLabel lblAlerta, JLabel lblIcono, JLabel lblPrecio, JLabel lblStock) {
        this.btnAstock = btnAstock;
        this.btnCprecio = btnCprecio;
        this.btnEproducto = btnEproducto;
        this.lblAlerta = lblAlerta;
        this.lblIcono = lblIcono;
        this.lblPrecio = lblPrecio;
        this.lblStock = lblStock;
    }
    

    public JButton getBtnAstock() {
        return btnAstock;
    }

    public void setBtnAstock(JButton btnAstock) {
        this.btnAstock = btnAstock;
    }

    public JButton getBtnCprecio() {
        return btnCprecio;
    }

    public void setBtnCprecio(JButton btnCprecio) {
        this.btnCprecio = btnCprecio;
    }

    public JButton getBtnEproducto() {
        return btnEproducto;
    }

    public void setBtnEproducto(JButton btnEproducto) {
        this.btnEproducto = btnEproducto;
    }

    public JLabel getLblAlerta() {
        return lblAlerta;
    }

    public void setLblAlerta(JLabel lblAlerta) {
        this.lblAlerta = lblAlerta;
    }

    public JLabel getLblCodigo() {
        return lblCodigo;
    }

    public void setLblCodigo(JLabel lblCodigo) {
        this.lblCodigo = lblCodigo;
    }

    public JLabel getLblEnstock() {
        return lblEnstock;
    }

    public void setLblEnstock(JLabel lblEnstock) {
        this.lblEnstock = lblEnstock;
    }

    public JLabel getLblEuro() {
        return lblEuro;
    }

    public void setLblEuro(JLabel lblEuro) {
        this.lblEuro = lblEuro;
    }

    public JLabel getLblIcono() {
        return lblIcono;
    }

    public void setLblIcono(JLabel lblIcono) {
        this.lblIcono = lblIcono;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblPrecio() {
        return lblPrecio;
    }

    public void setLblPrecio(JLabel lblPrecio) {
        this.lblPrecio = lblPrecio;
    }

    public JLabel getLblStock() {
        return lblStock;
    }

    public void setLblStock(JLabel lblStock) {
        this.lblStock = lblStock;
    }
    
    public void setPrecio(String precio) {
        lblPrecio.setText(precio);
    }
    
    public void setIcono(Icon icono) {
        lblIcono.setIcon(icono);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnAstock = new javax.swing.JButton();
        lblEnstock = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnCprecio = new javax.swing.JButton();
        btnEproducto = new javax.swing.JButton();
        lblEuro = new javax.swing.JLabel();
        lblMayoredad = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnAstock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAstock.setForeground(new java.awt.Color(0, 0, 0));
        btnAstock.setText("Añadir Stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(btnAstock, gridBagConstraints);

        lblEnstock.setForeground(new java.awt.Color(0, 0, 0));
        lblEnstock.setText("En Stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblEnstock, gridBagConstraints);

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("48392015");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        add(lblCodigo, gridBagConstraints);

        lblStock.setForeground(new java.awt.Color(0, 0, 0));
        lblStock.setText("100");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lblStock, gridBagConstraints);

        lblAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vacio.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        add(lblAlerta, gridBagConstraints);

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atun.png"))); // NOI18N
        lblIcono.setMaximumSize(new java.awt.Dimension(150, 150));
        lblIcono.setMinimumSize(new java.awt.Dimension(150, 150));
        lblIcono.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(lblIcono, gridBagConstraints);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Atún");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        add(lblNombre, gridBagConstraints);

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecio.setText("3,99");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        add(lblPrecio, gridBagConstraints);

        btnCprecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCprecio.setForeground(new java.awt.Color(0, 0, 0));
        btnCprecio.setText("Cambiar el precio");
        btnCprecio.setPreferredSize(new java.awt.Dimension(75, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(btnCprecio, gridBagConstraints);

        btnEproducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEproducto.setForeground(new java.awt.Color(0, 0, 0));
        btnEproducto.setText("Eliminar producto");
        btnEproducto.setPreferredSize(new java.awt.Dimension(75, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(btnEproducto, gridBagConstraints);

        lblEuro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEuro.setForeground(new java.awt.Color(0, 0, 0));
        lblEuro.setText("€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        add(lblEuro, gridBagConstraints);

        lblMayoredad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mas18.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        add(lblMayoredad, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAstock;
    private javax.swing.JButton btnCprecio;
    private javax.swing.JButton btnEproducto;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEnstock;
    private javax.swing.JLabel lblEuro;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMayoredad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    // End of variables declaration//GEN-END:variables
}
